// Bundles optimizer.js and its dependencies into one self-hosted ES module,
// so /developer and the Studio never depend on a third-party CDN for it.
//   cd tools/glb-optimizer && npm install && npm run build
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';

const here = (p) => fileURLToPath(new URL(p, import.meta.url));

await build({
  entryPoints: [here('./optimizer.js')],
  outfile: here('../../vendor/glb-optimizer.js'),
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: ['chrome100', 'safari16', 'firefox110'],
  minify: true,
  legalComments: 'none',
  banner: { js: '/* KARLCON GLB optimiser — generated by tools/glb-optimizer/build.mjs. Do not edit; edit optimizer.js. Includes glTF-Transform (MIT) and meshoptimizer (MIT). */' },
  external: ['node:fs', 'node:path'],   // only reached by glTF-Transform's NodeIO, never in the browser
  logLevel: 'info',
});
