/* KARLCON Studio — Season 3: THE CONCEPT ROOM.
   A new room, a full-size roof light on the platform, and the hosts on their feet. Each episode takes
   one type from the roof-light sheet (ridge, lean-to, shed, pyramid, ridge with gable ends, barrel vault,
   polygon), builds it in front of you part by part with the glazing-bar system (sill base, rafters,
   glazing tape, panels, pressure bars, snap caps), lets Karl walk up to it and work the vent, and picks
   a glass tint from the sample wall. Episode 8 is the system itself: every profile and every tint.
   Karl wears the KARLCON Elite Retreats worksuit here (KC_HOSTS.karl.outfitConcept).
   Extra cues in this room (studio.html):
     go: 'model' | 'screen' | 'tints' | 'profiles' | 'home'   walk the speaker there (goWho: the other host)
     touch: true      on arrival at the model, reach up and pull the vent sash (motion capture)
     tint: 'Euro Bronze' … (the sample sheet) or 'Polycarbonate'      cam: 'detail' follows the assembly
   House rules as always: no prices on air, engineering numbers only from the LB-1 file or the system's
   own install sheet (and said so), every KARLCON mechanism a concept until designed and tested.
   Play with /studio?season=3 (&ep=N), or `node render.mjs --season 3 --ep all`. */
(() => {
  const ROOM = 'concept';
  const STEPS = { kicker: 'How it goes together', title: 'The glazing-bar system', lines: ['Sill base on the kerb', 'Rafter bars up to the ridge', 'Glazing tape, then the panels', 'Pressure bars screwed down', 'Snap caps and perimeter caps'] };
  const HONEST = { kicker: 'Honest engineering', title: 'What is proven, what is concept', lines: ['Proven on LB-1: 555 N lift, 1,544 N wind hold per actuator', 'Glass: 10.38 heat-strengthened laminated', 'This roof light: a concept until designed and tested'] };
  const TINT = (a, b) => ({ kicker: 'Comment below', title: 'Which glass would you choose?', lines: [`Type 1: ${a}`, `Type 2: ${b}`] });
  const MYTH = (claim, verdict) => ({ kicker: 'Myth or fact', title: claim, lines: [verdict] });
  const next = (no, title) => ({ kicker: `Next · Episode ${no}`, title, lines: ['The Concept Room', 'Follow @karlcon_lumen_builds_zw'] });

  /* the assembly, the same order every time, told over five lines */
  const assemble = (name, extra = {}) => [
    { who: 'luma', cam: 'house', look: 'house', build: 0, open: 0, slide: STEPS, music: 'hype',
      say: `Let's build the ${name}. From the kerb up. Karl, talk us through it.` },
    { who: 'karl', cam: 'detail', look: 'house', build: 1,
      say: extra.sill || "It starts on a kerb, a raised upstand, so water can never sit at the edge. On top, the sill base, the aluminium profile everything else sits on." },
    { who: 'karl', cam: 'house', look: 'house', build: 2,
      say: extra.rafters || "Then the rafter bars, one after another, from the sill up to the ridge. They carry the glass, and they carry any water that gets past the seals down and out." },
    { who: 'karl', cam: 'detail', look: 'house', build: 4,
      say: extra.glass || "Glazing tape along every bar, so the glass never touches metal. Then the panels drop in, bay by bay." },
    { who: 'karl', cam: 'detail', look: 'house', build: 5,
      say: extra.bars || "Now the pressure bars. They clamp each panel down on its tape, and the screws go in every few hundred millimetres, all the way along." },
    { who: 'karl', cam: 'house', look: 'house', build: 7,
      say: extra.caps || "Last, the snap caps click over the pressure bars and hide the screws, and the perimeter caps close the edges. Water runs off the caps, and the job looks clean." }
  ];

  const list = window.KC_EPISODES_S3 = [{
    /* ================= S3 EPISODE 1 — The Ridge ================= */
    id: 's3e1-ridge', no: 1, season: 3, room: ROOM, music: 'groove',
    title: 'The Ridge Roof Light',
    subtitle: 'Season 3 · Episode 1 · The Concept Room · A long ridge with hipped ends',
    concept: 'ridge-skylight', city: 'harare',
    lines: [
      { who: 'luma', cam: 'wide', build: 7, open: 0, tint: 'Clear', mood: 'smile', look: 'camera', music: 'hype',
        slide: { kicker: 'Season 3 · The Concept Room', title: 'Seven roof lights, built in front of you', lines: ['Ridge, lean-to, shed, pyramid', 'Gable ridge, barrel vault, polygon', 'Episode 1: the ridge'] },
        say: "Welcome to season three of KARLCON Studios. New room. This is the Concept Room, and that is a full-size roof light standing right behind us." },
      { who: 'karl', cam: 'cu', mood: 'smile',
        say: "Good evening. Karl, in the Elite Retreats worksuit, because tonight we get our hands on it. Seven roof lights this season, one each episode. We start with the classic, the ridge." },
      { who: 'karl', cam: 'house', look: 'house', go: 'model', touch: true,
        say: "Come and have a look. A long run of glass, two slopes meeting at a ridge, and the ends are hipped, they slope down too, so there's glass on all four sides." },
      { who: 'luma', cam: 'two', look: 'other',
        say: "Where does a ridge like this go?" },
      { who: 'karl', cam: 'cu',
        say: "Over a long space. A corridor, a kitchen with a long island, a gallery, the middle of an open-plan lounge. It brings daylight down the whole length of the room, not just one spot." },
      { who: 'luma', cam: 'roof', look: 'roof', open: 1,
        say: "And these panels near the ridge open." },
      { who: 'karl', cam: 'roof', look: 'roof',
        say: "Two vents. Hot air rises to the ridge, the vents let it out, and the room stays cool. In a Harare October, that's the difference between a bright room and an oven." },
      { who: 'karl', cam: 'cu', mood: 'serious', slide: HONEST, open: 0,
        say: "Honest engineering. On KARLCON roofs the openers come from the actuator family we proved on LB-1, 555 newtons of lift and 1,544 newtons of wind hold each. A ridge vent like this is a concept until it's designed and tested." },
      ...assemble('ridge', { rafters: "Then the rafter bars, dozens of them on a ridge this long, parallel up both slopes. At the ends they stop on the hip bars, the diagonals that make the hipped ends." }),
      { who: 'luma', cam: 'wide', go: 'tints', music: 'calm',
        slide: { kicker: 'Glass tints', title: 'Twelve choices', lines: ['Clear and Ultra Clear', 'Bronzes, greys and blues', 'Two greens'] },
        say: "Now my favourite part. The glass. Let me walk you over to the samples." },
      { who: 'luma', cam: 'cu', look: 'tints',
        say: "Twelve tints on the sheet. For a long ridge over a kitchen, I'd go Blue Grey. It cools the light without making the room gloomy." },
      { who: 'karl', cam: 'house', look: 'house', tint: 'Blue Grey',
        say: "Blue Grey it is. Look how the whole run changes. Softer, cooler, and you still see the sky." },
      { who: 'luma', cam: 'two', mood: 'smile', slide: MYTH('“Tinted glass makes a room dark”', 'Myth: a light tint cuts glare, not daylight'),
        say: "Myth or fact. Tinted glass makes a room dark." },
      { who: 'karl', cam: 'cu',
        say: "Myth, with a light tint. You lose the glare and some of the heat, you keep the daylight. The dark tints, Black, Dark Grey, those are for places where you want shade first." },
      { who: 'luma', cam: 'two', go: 'home', mood: 'smile', slide: TINT('Clear', 'Blue Grey'),
        say: "Comment below. For your ridge, Clear, type 1, or Blue Grey, type 2?" },
      { who: 'karl', cam: 'cu', go: 'home', mood: 'smile',
        say: "I'm a 2. It looks expensive." },
      { who: 'luma', cam: 'wide', slide: next(2, 'The Lean-to'),
        say: "Next time, the lean-to, the roof light that leans on your wall. I'm Luma." },
      { who: 'karl', cam: 'wide', mood: 'smile',
        say: "And I'm Karl. See you in the Concept Room." }
    ]
  }, {
    /* ================= S3 EPISODE 2 — The Lean-to ================= */
    id: 's3e2-lean-to', no: 2, season: 3, room: ROOM, music: 'groove',
    title: 'The Lean-to Roof Light',
    subtitle: 'Season 3 · Episode 2 · The Concept Room · One slope against your wall',
    concept: 'lean-to-skylight', city: 'bulawayo',
    lines: [
      { who: 'luma', cam: 'wide', build: 7, open: 0, tint: 'Clear', mood: 'smile', look: 'camera', music: 'hype',
        slide: { kicker: 'Season 3 · Episode 2', title: 'The Lean-to', lines: ['One slope', 'Leans on a wall', 'Glass or multiwall'] },
        say: "Welcome back to the Concept Room. Tonight's roof light doesn't stand on its own. It leans." },
      { who: 'karl', cam: 'house', look: 'house', go: 'model', touch: true,
        say: "The lean-to. One slope of glass, high at the back where it meets the wall, low at the front, with glazed triangles at the sides. And two vents right at the top." },
      { who: 'luma', cam: 'two',
        say: "So it's for the edge of a house, not the middle." },
      { who: 'karl', cam: 'cu',
        say: "Exactly. A room built onto the side of the house, a stoep you want to close in, a passage along a wall. It turns the darkest strip of a house into the brightest." },
      { who: 'luma', cam: 'screen', look: 'screen', go: 'screen',
        slide: { kicker: 'The install sheet', title: 'Minimum pitch: 2 in 12', lines: ['Every installation on this system', 'About 9.5 degrees', 'So water always runs off'] },
        say: "The install sheet for this system has one rule printed at the bottom of every page." },
      { who: 'karl', cam: 'cu', mood: 'serious',
        say: "Minimum pitch, 2 in 12. That's about nine and a half degrees. Flatter than that and water sits on the glass. Every lean-to we draw starts from that line." },
      ...assemble('lean-to', { glass: "Glazing tape on every bar, then the panels. And here's a choice: glass, or twin-wall polycarbonate sheet, the ribbed plastic panel. Same bars, same caps." }),
      { who: 'luma', cam: 'house', look: 'house', tint: 'Polycarbonate', music: 'calm',
        slide: { kicker: 'Glass or multiwall?', title: 'Two ways to glaze it', lines: ['Glass: clear view, long life, heavier', 'Twin-wall polycarbonate: light, insulating, diffused light', 'Same glazing bars, same caps'] },
        say: "Show them the polycarbonate, Karl." },
      { who: 'karl', cam: 'detail', look: 'house',
        say: "Twin-wall polycarbonate. Two thin skins with ribs between them, so it's light and it insulates. You don't see the sky through it, the light comes through soft and even. Good over a workshop or a carport." },
      { who: 'luma', cam: 'house', look: 'house', tint: 'Euro Grey',
        say: "And back to glass. Euro Grey." },
      { who: 'karl', cam: 'house', look: 'house', open: 1,
        say: "Glass for a room you live in. You want to look up and see the sky. And the vents at the top let the heat out along the wall." },
      { who: 'luma', cam: 'two', open: 0, mood: 'smile', slide: MYTH('“A lean-to has to be glued to the wall”', 'Myth: it is flashed and fixed, never just glued'),
        say: "Myth or fact. A lean-to is just glued onto the wall." },
      { who: 'karl', cam: 'cu', mood: 'serious',
        say: "Myth. The high edge is fixed to the structure and flashed into the wall, so water running down the wall goes over the top of the glass, not behind it. Glue alone fails." },
      { who: 'luma', cam: 'two', go: 'home', slide: TINT('Glass', 'Twin-wall polycarbonate'),
        say: "Comment below. Glass, type 1, or polycarbonate, type 2? And tell us what room it's for." },
      { who: 'karl', cam: 'cu', go: 'home', mood: 'smile',
        say: "Glass for living, poly for working. That's my rule." },
      { who: 'luma', cam: 'wide', slide: next(3, 'The Shed'),
        say: "Next time, the shed, a whole glass room. I'm Luma." },
      { who: 'karl', cam: 'wide', mood: 'smile',
        say: "I'm Karl. See you in the Concept Room." }
    ]
  }, {
    /* ================= S3 EPISODE 3 — The Shed ================= */
    id: 's3e3-shed', no: 3, season: 3, room: ROOM, music: 'groove',
    title: 'The Glass Shed',
    subtitle: 'Season 3 · Episode 3 · The Concept Room · Four glass walls and a sloping roof',
    concept: 'shed-skylight', city: 'mutare',
    lines: [
      { who: 'luma', cam: 'wide', build: 7, open: 0, tint: 'Clear', mood: 'smile', look: 'camera', music: 'hype',
        slide: { kicker: 'Season 3 · Episode 3', title: 'The Shed', lines: ['Four glazed walls', 'A monopitch roof', 'A vent in the roof'] },
        say: "Tonight in the Concept Room, the roof light that became a room. The glass shed." },
      { who: 'karl', cam: 'house', look: 'house', go: 'model', touch: true,
        say: "Four glass walls on a kerb, and a roof that slopes one way, higher at the back. Same bars as the roof lights, standing up. And a vent in the roof." },
      { who: 'luma', cam: 'two',
        say: "Who builds a glass shed?" },
      { who: 'karl', cam: 'cu', mood: 'smile',
        say: "Gardeners, first. Seedlings love it. But also a reading nook in the garden, a small office, a pool room. In Mutare's rain you sit inside and watch the storm come over the mountains." },
      ...assemble('shed', { rafters: "Then the bars. On the walls they stand straight up, mullions. On the roof they run from the low front to the high back. Where they meet, a corner bar ties the wall to the roof." }),
      { who: 'luma', cam: 'screen', look: 'screen', go: 'screen',
        slide: { kicker: 'The install sheet', title: 'Where the glass meets the sill', lines: ['Perimeter cap over the glass edge', 'Glazing tape under it', 'Weep holes so water gets out'] },
        say: "The corners are where things leak, right?" },
      { who: 'karl', cam: 'cu', mood: 'serious',
        say: "The edges. So at the bottom, the perimeter cap sits over the glass edge on its tape, and the install sheet shows small drilled weep holes in the sill, so any water that gets in has a way out. Water you plan for doesn't hurt you." },
      { who: 'luma', cam: 'wide', go: 'tints', music: 'calm',
        say: "For a garden room, what glass?" },
      { who: 'luma', cam: 'cu', look: 'tints',
        say: "I'm looking at F-Green. It's the palest green on the sheet, it would sit so well in a garden." },
      { who: 'karl', cam: 'house', look: 'house', tint: 'F-Green', open: 1,
        say: "F-Green. And the roof vent open. That's a garden room." },
      { who: 'luma', cam: 'two', open: 0, mood: 'smile', slide: MYTH('“A glass room is always too hot”', 'Only if it cannot breathe or be shaded'),
        say: "Myth or fact. A glass room is always too hot." },
      { who: 'karl', cam: 'cu',
        say: "Only if it can't breathe. A roof vent, a door that opens, a tree on the west side, a tinted roof. Then it's the best room on the property." },
      { who: 'luma', cam: 'two', go: 'home', slide: { kicker: 'Comment below', title: 'What would your glass shed be?', lines: ['Type 1: garden room', 'Type 2: office or studio'] },
        say: "Comment below. Your glass shed. Type 1, garden room. Type 2, office or studio." },
      { who: 'karl', cam: 'cu', go: 'home', mood: 'smile',
        say: "An office where you can't hear the house. I'd never leave it." },
      { who: 'luma', cam: 'wide', slide: next(4, 'The Pyramid'),
        say: "Next time, the pyramid. I'm Luma." },
      { who: 'karl', cam: 'wide', mood: 'smile',
        say: "I'm Karl. See you in the Concept Room." }
    ]
  }, {
    /* ================= S3 EPISODE 4 — The Pyramid ================= */
    id: 's3e4-pyramid', no: 4, season: 3, room: ROOM, music: 'groove',
    title: 'The Pyramid Roof Light',
    subtitle: 'Season 3 · Episode 4 · The Concept Room · Four slopes to one point',
    concept: 'pyramid-skylight', city: 'masvingo',
    lines: [
      { who: 'luma', cam: 'wide', build: 7, open: 0, tint: 'Clear', mood: 'smile', look: 'camera', music: 'hype',
        slide: { kicker: 'Season 3 · Episode 4', title: 'The Pyramid', lines: ['A square base', 'Four slopes to one point', 'The centrepiece roof light'] },
        say: "Tonight's roof light is the one people point at. Welcome to the Concept Room. The pyramid." },
      { who: 'karl', cam: 'house', look: 'house', go: 'model', touch: true,
        say: "A square kerb, four glass slopes rising to one point. Look at the bars. They run parallel up each face and stop on the four hips, the bars that come down from the top to the corners." },
      { who: 'luma', cam: 'two',
        say: "It's a statement." },
      { who: 'karl', cam: 'cu', mood: 'smile',
        say: "It is. Over an entrance hall, over a stairwell, over the dining table. You put a pyramid where you want people to stop and look up." },
      ...assemble('pyramid', { rafters: "Then the hips first, the four corner bars to the apex, and the rafters in between, parallel, shorter and shorter as they near the corners. Every one cut to meet the hip at its own length." }),
      { who: 'luma', cam: 'roof', look: 'roof', open: 1,
        say: "And the vents on the front face." },
      { who: 'karl', cam: 'roof', look: 'roof',
        say: "The top of a pyramid is the highest point in the room, so it's where the hot air collects. Open two panels on the face, and the whole room breathes out through the top." },
      { who: 'karl', cam: 'cu', mood: 'serious', slide: HONEST, open: 0,
        say: "If we motorise those, it's the same actuator family we proved on LB-1. 555 newtons of lift, 1,544 newtons of wind hold, each. For a pyramid face it's a concept until the engineer sizes it." },
      { who: 'luma', cam: 'wide', go: 'tints', music: 'calm',
        say: "Time to choose. Near Great Zimbabwe, with all that granite, I'm thinking warm." },
      { who: 'luma', cam: 'cu', look: 'tints',
        say: "Golden Bronze. It turns the midday light the colour of late afternoon." },
      { who: 'karl', cam: 'house', look: 'house', tint: 'Golden Bronze',
        say: "Golden Bronze on a pyramid. Now that's a centrepiece." },
      { who: 'luma', cam: 'two', mood: 'smile', slide: MYTH('“A pyramid is harder to keep watertight”', 'More joints, so the detailing matters more'),
        say: "Myth or fact. A pyramid is harder to keep watertight than a flat roof light." },
      { who: 'karl', cam: 'cu',
        say: "Partly fact. More bars, more joints, and the hips carry water from two faces. But it's steep, so water runs off fast. Get the hip caps and the tape right, and it's dry." },
      { who: 'luma', cam: 'two', go: 'home', slide: TINT('Golden Bronze', 'Clear'),
        say: "Comment below. Pyramid in Golden Bronze, type 1, or Clear, type 2?" },
      { who: 'karl', cam: 'cu', go: 'home', mood: 'smile',
        say: "Bronze. Every time." },
      { who: 'luma', cam: 'wide', slide: next(5, 'The Gable Ridge'),
        say: "Next time, the ridge again, with a twist. Glass gables. I'm Luma." },
      { who: 'karl', cam: 'wide', mood: 'smile',
        say: "I'm Karl. See you in the Concept Room." }
    ]
  }, {
    /* ================= S3 EPISODE 5 — Ridge with Gable Ends ================= */
    id: 's3e5-gable-ridge', no: 5, season: 3, room: ROOM, music: 'groove',
    title: 'The Gable Ridge',
    subtitle: 'Season 3 · Episode 5 · The Concept Room · A ridge with glass gable ends',
    concept: 'gable-ridge-skylight', city: 'harare',
    lines: [
      { who: 'luma', cam: 'wide', build: 7, open: 0, tint: 'Clear', mood: 'smile', look: 'camera', music: 'hype',
        slide: { kicker: 'Season 3 · Episode 5', title: 'Ridge with gable ends', lines: ['Two slopes to a ridge', 'Upright glass triangles at the ends', 'Vents along the ridge'] },
        say: "Welcome back to the Concept Room. Remember the ridge from episode one? Tonight, its sharper cousin." },
      { who: 'karl', cam: 'house', look: 'house', go: 'model', touch: true,
        say: "The gable ridge. Two slopes up to a ridge that runs the full length, and instead of hipped ends, the ends stand up straight. Glass gables, like the end of a house." },
      { who: 'luma', cam: 'two',
        say: "Why choose gables over hips?" },
      { who: 'karl', cam: 'cu',
        say: "Height and light. The gable ends are vertical glass, so you get light from the ends too, and the ridge carries its full height all the way along. It looks like a little glass house on the roof." },
      ...assemble('gable ridge', { caps: "Last, the snap caps, and the perimeter caps. On the gables, the edge cap turns the corner and closes the end of the ridge. The install sheet even shows the snap cap cut and folded to close its own open end, sealed with silicone." }),
      { who: 'luma', cam: 'screen', look: 'screen', go: 'screen',
        slide: { kicker: 'The install sheet', title: 'What holds it down', lines: ['Self-sealing screws through the pressure bar', 'Every few hundred millimetres', 'Oversized holes in multiwall sheet, so it can move'] },
        say: "Let's talk screws. The sheet has a lot to say about them." },
      { who: 'karl', cam: 'cu',
        say: "It does. Self-sealing screws through the pressure bar into the rafter, close together, and where a polycarbonate sheet spans a rafter, the hole is drilled oversized so the sheet can expand in the heat without cracking." },
      { who: 'luma', cam: 'roof', look: 'roof', open: 1,
        say: "And the vents along the ridge." },
      { who: 'karl', cam: 'roof', look: 'roof',
        say: "High, so the hottest air goes first. With glass gables you can even open the ends for a cross-breeze." },
      { who: 'luma', cam: 'wide', go: 'tints', open: 0, music: 'calm',
        say: "Tint time." },
      { who: 'luma', cam: 'cu', look: 'tints',
        say: "For something this architectural, Dark Grey. Moody, sharp, very modern." },
      { who: 'karl', cam: 'house', look: 'house', tint: 'Dark Grey',
        say: "Dark Grey. That's a design statement. Softer light underneath, and from the street it reads like black glass." },
      { who: 'luma', cam: 'two', go: 'home', mood: 'smile', slide: TINT('Dark Grey', 'Ultra Clear'),
        say: "Comment below. Dark Grey, type 1, or Ultra Clear, type 2, the clearest glass on the sheet?" },
      { who: 'karl', cam: 'cu', go: 'home', mood: 'smile',
        say: "Grey outside, bright inside. I'll take 1." },
      { who: 'luma', cam: 'wide', slide: next(6, 'The Barrel Vault'),
        say: "Next time, the barrel vault, a curve made of straight lines. I'm Luma." },
      { who: 'karl', cam: 'wide', mood: 'smile',
        say: "I'm Karl. See you in the Concept Room." }
    ]
  }, {
    /* ================= S3 EPISODE 6 — Barrel Vault ================= */
    id: 's3e6-barrel-vault', no: 6, season: 3, room: ROOM, music: 'groove',
    title: 'The Barrel Vault',
    subtitle: 'Season 3 · Episode 6 · The Concept Room · An arch of glass',
    concept: 'barrel-vault-skylight', city: 'vicfalls',
    lines: [
      { who: 'luma', cam: 'wide', build: 7, open: 0, tint: 'Clear', mood: 'smile', look: 'camera', music: 'hype',
        slide: { kicker: 'Season 3 · Episode 6', title: 'The Barrel Vault', lines: ['Low glass walls', 'A faceted arch over them', 'Glazed ends'] },
        say: "Tonight in the Concept Room, a roof light that looks curved, and isn't. The barrel vault." },
      { who: 'karl', cam: 'house', look: 'house', go: 'model', touch: true,
        say: "Low glass walls on the kerb, and an arch of glass over them. Look closely. The arch is made of flat panels, six facets, each one a straight run of glass. Flat glass, curved look." },
      { who: 'luma', cam: 'two',
        say: "Why facets and not bent glass?" },
      { who: 'karl', cam: 'cu',
        say: "Bent glass is special order, slow and expensive, and hard to replace. Flat panels are standard, any glazier can cut one, and with six facets your eye reads a curve." },
      ...assemble('barrel vault', { rafters: "Then the arch bars, one arch after another along the length, each one six straight pieces. And the ends, a fan of bars from the springing line up to the arch." }),
      { who: 'luma', cam: 'roof', look: 'roof', open: 1,
        say: "Vents in the arch." },
      { who: 'karl', cam: 'roof', look: 'roof',
        say: "Up in the third facet, near the crown. That's where the heat gathers under a vault. Near the Falls, with all that humidity, you want that air moving." },
      { who: 'luma', cam: 'wide', go: 'tints', open: 0, music: 'calm',
        say: "For a vault near the Zambezi, something with water in it." },
      { who: 'luma', cam: 'cu', look: 'tints',
        say: "Ford Blue. It's the colour of the sky over the river." },
      { who: 'karl', cam: 'house', look: 'house', tint: 'Ford Blue',
        say: "Ford Blue on a vault. That's a pool house, or a covered walkway to the lodge." },
      { who: 'luma', cam: 'two', mood: 'smile', slide: MYTH('“Curved roofs need curved glass”', 'Myth: flat facets make the curve'),
        say: "Myth or fact. A curved roof needs curved glass." },
      { who: 'karl', cam: 'cu',
        say: "Myth. You just saw it. Six flat facets and nobody at the pool will ever know." },
      { who: 'luma', cam: 'two', go: 'home', slide: { kicker: 'Comment below', title: 'Where would your vault go?', lines: ['Type 1: over a pool', 'Type 2: over a walkway'] },
        say: "Comment below. A glass vault over a pool, type 1, or over a walkway, type 2?" },
      { who: 'karl', cam: 'cu', go: 'home', mood: 'smile',
        say: "Pool. Swimming under the sky, in the rain. Come on." },
      { who: 'luma', cam: 'wide', slide: next(7, 'The Polygon'),
        say: "Next time, the last shape of the season, the polygon. I'm Luma." },
      { who: 'karl', cam: 'wide', mood: 'smile',
        say: "I'm Karl. See you in the Concept Room." }
    ]
  }, {
    /* ================= S3 EPISODE 7 — The Polygon ================= */
    id: 's3e7-polygon', no: 7, season: 3, room: ROOM, music: 'groove',
    title: 'The Polygon Roof Light',
    subtitle: 'Season 3 · Episode 7 · The Concept Room · Twelve sides, one crown',
    concept: 'polygon-skylight', city: 'masvingo',
    lines: [
      { who: 'luma', cam: 'wide', build: 7, open: 0, tint: 'Clear', mood: 'smile', look: 'camera', music: 'hype',
        slide: { kicker: 'Season 3 · Episode 7', title: 'The Polygon', lines: ['Twelve sides', 'Radial bars to a hub', 'A crown of glass'] },
        say: "The last shape of the season. Welcome to the Concept Room, and to the polygon." },
      { who: 'karl', cam: 'house', look: 'house', go: 'model', touch: true,
        say: "Twelve sides on a round kerb. The bars run from the rim to a hub at the crown, like the spokes of a wheel, with a ring bar half way up. And every third panel on the lower ring opens." },
      { who: 'luma', cam: 'two',
        say: "It feels like it belongs over a round room." },
      { who: 'karl', cam: 'cu', mood: 'smile',
        say: "It does, and that's why we love it. Put it over a rondavel, and you've got season two and season three in one building. A round room, with a crown of glass." },
      ...assemble('polygon', { rafters: "Then the hub goes up first, in the middle, and the spokes run out from it to every corner of the kerb. Then the ring bar ties them together half way.", glass: "Tape on every spoke, then the panels, trapezoids on the lower ring and small triangles at the crown. Twenty-four pieces of glass." }),
      { who: 'luma', cam: 'roof', look: 'roof', open: 1,
        say: "And the vents all round the ring." },
      { who: 'karl', cam: 'roof', look: 'roof',
        say: "Four of them, spaced round the circle, so whichever way the wind blows, air can get in on one side and out the other." },
      { who: 'karl', cam: 'cu', mood: 'serious', slide: HONEST, open: 0,
        say: "Honest engineering. Motorised vents come from the actuator family proven on LB-1. On a twelve-sided crown, it's a concept until it's designed and tested." },
      { who: 'luma', cam: 'wide', go: 'tints', music: 'calm',
        say: "The last tint of the season. I'm going bold." },
      { who: 'luma', cam: 'cu', look: 'tints',
        say: "Dark Blue. Over a round room, it'll feel like being under the night sky, even at noon." },
      { who: 'karl', cam: 'house', look: 'house', tint: 'Dark Blue',
        say: "Dark Blue on the polygon. A little planetarium." },
      { who: 'luma', cam: 'two', mood: 'smile', slide: MYTH('“A round roof light needs round glass”', 'Myth: straight edges, flat panels'),
        say: "Myth or fact. A round roof light needs round glass." },
      { who: 'karl', cam: 'cu',
        say: "Myth. Twelve straight sides, flat panels, every one cut from a standard sheet. Round is a trick of the eye." },
      { who: 'luma', cam: 'two', go: 'home', slide: { kicker: 'Comment below', title: 'Which shape did you like best?', lines: ['Type the shape: ridge, lean-to, shed', 'pyramid, gable, vault or polygon'] },
        say: "Seven shapes. Which one is yours? Type it in the comments, we'll count them." },
      { who: 'karl', cam: 'cu', go: 'home', mood: 'smile',
        say: "I'm not allowed to vote. But it's the pyramid." },
      { who: 'luma', cam: 'wide', slide: next(8, 'The System'),
        say: "Next time, the finale. No new shape. The system itself, every piece and every tint. I'm Luma." },
      { who: 'karl', cam: 'wide', mood: 'smile',
        say: "I'm Karl. See you in the Concept Room." }
    ]
  }, {
    /* ================= S3 EPISODE 8 — The System (profiles and tints) ================= */
    id: 's3e8-system', no: 8, season: 3, room: ROOM, music: 'groove',
    title: 'The System: Every Piece, Every Tint',
    subtitle: 'Season 3 · Episode 8 · The Concept Room · The glazing-bar system and the twelve tints',
    concept: 'pyramid-skylight', city: 'harare',
    lines: [
      { who: 'luma', cam: 'wide', build: 7, open: 0, tint: 'Clear', mood: 'smile', look: 'camera', music: 'hype',
        slide: { kicker: 'Season 3 · Finale', title: 'The system', lines: ['Every profile', 'Every tint', 'One roof light, taken apart and put back'] },
        say: "The season three finale in the Concept Room. Seven shapes, one system. Tonight, the pieces." },
      { who: 'karl', cam: 'wide', go: 'profiles',
        say: "Come with me to the board. Every roof light this season was built from the same six pieces." },
      { who: 'karl', cam: 'cu', look: 'profiles',
        slide: { kicker: 'The glazing-bar system', title: 'Six pieces', lines: ['1000 sill base', '1001 rafter base', 'Glazing tape', '4009 pressure bar', '4008 snap cap', '3919 perimeter cap'] },
        say: "The sill base sits on the kerb. The rafter base is the bar everything hangs on. Glazing tape keeps glass off metal. The pressure bar clamps the glass. The snap cap hides the screws. The perimeter cap closes the edges." },
      { who: 'luma', cam: 'two', look: 'other',
        say: "And those numbers?" },
      { who: 'karl', cam: 'cu',
        say: "The part numbers on the install sheet for this system. When you order, you order by those. Different makers, different numbers, same idea." },
      { who: 'luma', cam: 'house', look: 'house', build: 0,
        say: "Let's take the pyramid apart, and put it back together, slowly." },
      { who: 'karl', cam: 'detail', look: 'house', build: 1, go: 'model',
        say: "Kerb. Then the sill base, all round. Check it's level, because every bar above it takes its line from here." },
      { who: 'karl', cam: 'detail', look: 'house', build: 2,
        say: "Rafter bars. Each one sits on the sill and runs to the hip or the ridge. On the install sheet, the rafter base has two flanges, and the tape and the glass sit on those." },
      { who: 'karl', cam: 'detail', look: 'house', build: 3,
        say: "Glazing tape. A thin strip down both flanges of every bar. Glass never touches aluminium." },
      { who: 'karl', cam: 'detail', look: 'house', build: 4,
        say: "Panels. Lowered in, one bay at a time, each one resting on tape on both sides." },
      { who: 'karl', cam: 'detail', look: 'house', build: 5,
        say: "Pressure bars, down the middle of every rafter, and the screws. Watch the drill. The sheet says close spacing, self-sealing screws." },
      { who: 'karl', cam: 'house', look: 'house', build: 7, touch: true, go: 'model',
        say: "And the caps. Snap caps click on, perimeter caps close the edges. Done. That's how every roof light this season went together." },
      { who: 'luma', cam: 'wide', go: 'tints', music: 'calm',
        slide: { kicker: 'Glass tints', title: 'All twelve', lines: ['Clear · Ultra Clear', 'Euro Bronze · Golden Bronze', 'Black · Euro Grey · Dark Grey', 'Blue Grey · Ford Blue · Dark Blue', 'Dark Green · F-Green'] },
        say: "Now the fun part. All twelve tints, on the pyramid. Karl, you run the glass, I'll call them." },
      { who: 'luma', cam: 'house', look: 'house', tint: 'Ultra Clear',
        say: "Ultra Clear. The clearest glass there is, almost no colour at all." },
      { who: 'luma', cam: 'house', look: 'house', tint: 'Euro Bronze',
        say: "Euro Bronze. Warm, soft, a classic." },
      { who: 'luma', cam: 'house', look: 'house', tint: 'Black',
        say: "Black. Maximum shade, maximum drama." },
      { who: 'luma', cam: 'house', look: 'house', tint: 'Euro Grey',
        say: "Euro Grey. Neutral. Cuts the glare, keeps the colours true." },
      { who: 'luma', cam: 'house', look: 'house', tint: 'Blue Grey',
        say: "Blue Grey. Cool and calm." },
      { who: 'luma', cam: 'house', look: 'house', tint: 'Ford Blue',
        say: "Ford Blue. Sky over water." },
      { who: 'luma', cam: 'house', look: 'house', tint: 'Dark Green',
        say: "Dark Green. Like standing under a tree." },
      { who: 'luma', cam: 'house', look: 'house', tint: 'Golden Bronze',
        say: "And Golden Bronze. Late afternoon, all day." },
      { who: 'karl', cam: 'cu', go: 'home', mood: 'serious', slide: HONEST,
        say: "One honest word to finish. The shapes and the glazing system are how the industry has built roof lights for years. The KARLCON part, the openers, the rain sensors, the controls, comes from LB-1, and every new version is a concept until it's designed and tested." },
      { who: 'luma', cam: 'two', go: 'home', mood: 'smile', slide: { kicker: 'Comment below', title: 'Your roof light', lines: ['Tell us: shape + tint', 'e.g. “pyramid, Golden Bronze”', 'Follow @karlcon_lumen_builds_zw'] },
        say: "Your turn. Shape and tint, in the comments. Pyramid in Golden Bronze, ridge in Blue Grey, whatever you'd put on your roof." },
      { who: 'karl', cam: 'cu', mood: 'smile',
        say: "And if you want one on your actual roof, message us. We'll start in the Concept Room." },
      { who: 'luma', cam: 'wide', mood: 'smile',
        slide: { kicker: 'Season 3', title: 'The Concept Room', lines: ['Seven roof lights', 'One glazing system', 'Twelve tints'] },
        say: "That's season three, the Concept Room. Thank you for building with us. I'm Luma." },
      { who: 'karl', cam: 'wide', mood: 'smile',
        say: "I'm Karl. Look up. See you next season." }
    ]
  }];
  void list;
})();
