/* KARLCON Studio — hosts and episode scripts.
   House rule from concepts-data.js: engineering numbers only appear where they come from the
   LB-1 engineering file. Everything else is described, not quantified, until it is designed.

   HOSTS — `model` is any TalkingHead-compatible GLB (Avaturn T2, AvatarSDK MetaPerson, MPFB).
   The two realistic sample avatars below come from the open-source TalkingHead project and are
   licensed for NON-COMMERCIAL use only. They are stand-ins for rehearsal. Before a public or
   sponsored broadcast, swap in avatars you own (e.g. make your own from photos at avaturn.me and
   follow its commercial terms) or use /models/hosts/mpfb.glb, which is CC0.

   LINE CUES (all optional)
     cam:     'wide' | 'two' | 'cu' (speaker close-up) | 'house' | 'roof' | 'globe' | 'screen' | 'desk'
     look:    where BOTH hosts look — 'house' | 'globe' | 'screen' | 'camera'
     point:   true → the speaker gestures at the building
     build:   0–7 → animate the building to that construction stage
              0 footings · 1 columns · 2 floor · 3 walls+roof · 4 glazing · 5 interior · 6 roof light · 7 complete
     open:    0–1 → roof light leaves (1 = fully open, with the daylight shaft)
     slide:   { kicker, title, lines[] } → the story screen and the on-air topic bar
     ticker:  [strings] → the scrolling materials ticker
     mood:    'smile' | 'serious'
*/
window.KC_HOSTS = {
  luma: {
    name: 'Luma', role: 'Host · KARLCON Systems Intelligence', seat: 0,
    model: '/models/hosts/avaturn.glb', fallback: '/models/hosts/mpfb.glb',
    voice: { gender: 'female', prefer: ['Ava', 'Aria', 'Jenny', 'Sonia', 'Libby', 'Samantha', 'Google UK English Female', 'Zira', 'Female'] },
    pitch: 1.04, rate: 1.0, mouthGain: 0.7
  },
  karl: {
    name: 'Karl', role: 'Engineer · KARLCON Lumen Builds', seat: 1,
    model: '/models/hosts/avatarsdk.glb', fallback: '/models/hosts/mpfb.glb',
    voice: { gender: 'male', prefer: ['Andrew', 'Guy', 'Ryan', 'Thomas', 'Daniel', 'Google UK English Male', 'David', 'Male'] },
    pitch: 0.96, rate: 0.98, mouthGain: 0.9
  }
};

const MATERIALS_CUBE = [
  'Concrete pad footings, reinforced', 'Hold-down bolts + non-shrink grout', 'Steel columns — galvanised, signal-red finish',
  'Steel floor and roof beams', 'Insulated walls, white render', 'Full-height glazing in dark aluminium frames',
  'Roof light: 10.38 heat-strengthened laminated glass', 'Aluminium kerb + EPDM seals', '2 actuators · 555 N lift · 1,544 N wind hold each',
  'Rain sensor + controller', 'Battery backup + manual override', 'Waterproof membrane + flashings'
];

window.KC_EPISODES = [{
  id: 'ep1-glass-cube', no: 1,
  title: 'The Elevated Glass Cube',
  subtitle: 'Episode 1 · Harare · How a lifted box earns its roof light',
  concept: 'cantilever-pavilion',
  city: 'harare',
  lines: [
    { who: 'luma', cam: 'wide', build: 7, open: 0, mood: 'smile',
      slide: { kicker: 'Episode 1 · Harare', title: 'The Elevated Glass Cube', lines: ['A glazed living box lifted on four red columns', 'A bi-parting roof light right over the lounge'] },
      say: "Good evening, and welcome to KARLCON Systems Intelligence. I'm Luma, and tonight we're in Harare, looking at a house that floats." },
    { who: 'karl', cam: 'cu', mood: 'smile',
      say: "Evening everyone. Karl here, from Lumen Builds. And yes, it floats. Well, almost. It's a glass box standing on four red steel columns." },
    { who: 'luma', cam: 'two',
      say: "So Karl, the question everybody asks in the comments. Why lift the house at all?" },
    { who: 'karl', cam: 'house', look: 'house', point: true,
      say: "Three reasons. You get a view over the wall and the jacaranda trees. You get shade and a dry parking space underneath. And the living room sits above the dust and the storm water in the rainy season." },
    { who: 'luma', cam: 'cu',
      say: "Okay, but a glass box in the Zimbabwean sun. Isn't that a greenhouse?" },
    { who: 'karl', cam: 'cu', mood: 'serious',
      say: "It would be, if you did it lazily. The glass has to be chosen for heat, not just for looks. That's why our planner shows how much heat each glass lets in before we size anything." },
    { who: 'luma', cam: 'roof', look: 'house', open: 0,
      slide: { kicker: 'Roof light', title: 'Bi-parting hinged roof light', lines: ['Two glass leaves lift apart from the centre', 'Paired actuators, one per leaf', 'Benchmark aperture 1.5 × 2.0 m'] },
      say: "And the star of the show is up on the roof. Karl, show them." },
    { who: 'karl', cam: 'roof', look: 'house', open: 1,
      say: "Watch the roof. Two glass leaves lift apart from the centre, on paired actuators, and the lounge opens straight to the sky." },
    { who: 'luma', cam: 'cu', mood: 'smile',
      say: "That's the Iron Man moment right there. What's actually lifting that glass?" },
    { who: 'karl', cam: 'cu',
      slide: { kicker: 'From the LB-1 engineering file', title: 'The numbers behind the reveal', lines: ['Benchmark aperture: 1.5 × 2.0 m', 'Lift force: 555 newtons per actuator', 'Wind hold: 1,544 newtons per actuator', 'Glass: 10.38 heat-strengthened laminated'] },
      say: "On our benchmark opening of one and a half by two metres, each actuator lifts with 555 newtons. But the bigger number is the hold. In a storm, each one holds 1,544 newtons so the wind can't rip the leaf open." },
    { who: 'luma', cam: 'two',
      say: "And the glass itself?" },
    { who: 'karl', cam: 'cu',
      say: "Ten point three eight heat-strengthened laminated. If it ever cracks, the layer in the middle holds it together. Nobody wants glass falling on the sofa." },
    { who: 'luma', cam: 'globe', look: 'globe',
      slide: { kicker: 'Grounded in Zimbabwe', title: 'Designing for our climate', lines: ['Summer storms: rain sensor closes the roof', 'Strong sun: glass chosen for heat', 'Power cuts: battery backup + manual override', 'Termites + clay soils: steel, concrete, a soil check'] },
      say: "Let's ground this in Zimbabwe. Afternoon thunderstorms, load-shedding, termites. What changes?" },
    { who: 'karl', cam: 'cu', mood: 'serious',
      say: "Everything. A rain sensor closes the roof before the first drops reach the couch. The controller runs on battery backup, with a manual override, so a power cut never leaves your roof open. And at ground level it's steel and concrete, not timber, because termites don't eat either." },
    { who: 'luma', cam: 'two',
      say: "And the ground itself? Some parts of Harare have that heavy clay." },
    { who: 'karl', cam: 'cu',
      say: "Exactly. Before we pour anything, we test the soil. On clay that swells in the rains, the engineer sets how deep the footings go. We don't guess that." },
    { who: 'luma', cam: 'house', look: 'house', build: 0,
      slide: { kicker: 'Build sequence', title: 'How it goes up, step by step', lines: ['Survey and soil test', 'Pad footings with hold-down bolts', 'Columns erected and grouted', 'Floor deck, walls and roof frame'] },
      say: "Right, let's build it. Karl, take us from bare ground." },
    { who: 'karl', cam: 'house', look: 'house', build: 1, point: true,
      say: "Step one, survey and soil test. Step two, four concrete pad footings with hold-down bolts cast in. Step three, the red steel columns go up and get grouted to the bolts." },
    { who: 'karl', cam: 'house', look: 'house', build: 3,
      say: "Then the floor deck is lifted into place, and the walls and roof frame go on top. Now it's a box in the air." },
    { who: 'karl', cam: 'house', look: 'house', build: 5,
      slide: { kicker: 'Build sequence', title: 'Closing it in', lines: ['Full-height glazing in aluminium frames', 'Interior fit-out', 'Roof light kerb, leaves and actuators', 'Water test before handover'] },
      say: "Full-height glazing goes into dark aluminium frames. Aluminium is our home ground, we fabricate it ourselves." },
    { who: 'karl', cam: 'roof', look: 'house', build: 7, open: 0,
      say: "Last, the roof light. Kerb, seals, leaves, actuators, and then we water-test it on the rig before it goes anywhere near a client." },
    { who: 'luma', cam: 'screen', look: 'screen',
      slide: { kicker: 'Materials list', title: 'What goes into the Glass Cube', lines: ['Concrete footings, bolts, grout', 'Galvanised steel columns and beams', 'Insulated walls, white render', 'Aluminium-framed glazing', 'Laminated roof light, seals, actuators', 'Rain sensor, battery backup'] },
      ticker: MATERIALS_CUBE,
      say: "For everyone taking notes, here's the full materials list on screen now." },
    { who: 'luma', cam: 'two',
      say: "Last question. How does a concept like this become a 3D model you can walk around?" },
    { who: 'karl', cam: 'cu',
      say: "We start with the render. The building is cut out and turned into a 3D model, then we add the real mechanism with the real numbers. Wind uplift, glass stress and deflection get checked, and it stays labelled concept until it's built and water-tested." },
    { who: 'luma', cam: 'wide', open: 1, mood: 'smile',
      slide: { kicker: 'Next episode', title: 'Where should the Atlas fly next?', lines: ['Bulawayo · Mutare · Masvingo · Victoria Falls', 'Drop your city in the comments', 'Follow @karlcon_lumen_builds_zw'] },
      say: "That's the Glass Cube. Next episode we fly the Atlas to another city and find a house that deserves a roof light. Drop your city in the comments. I'm Luma." },
    { who: 'karl', cam: 'wide', mood: 'smile',
      say: "And I'm Karl. Thanks for watching. Go and follow the build." }
  ]
}, {
  /* ================= EPISODE 2 — Lumen Oval Residence · Victoria Falls ================= */
  id: 'ep2-lumen-oval', no: 2,
  title: 'The Lumen Oval',
  subtitle: 'Episode 2 · Victoria Falls · A roof that slides away like a telescope',
  concept: 'lumen-oval-residence', city: 'vicfalls',
  lines: [
    { who: 'luma', cam: 'wide', build: 7, open: 0, mood: 'smile', look: 'globe',
      slide: { kicker: 'Episode 2 · Victoria Falls', title: 'The Lumen Oval', lines: ['A two-storey white oval', 'A wraparound terrace', 'A curved glass roof that slides away'] },
      say: "Welcome back to KARLCON Systems Intelligence. The Atlas has flown us to Victoria Falls, the town beside the waterfall on the Zambezi, and tonight's house has no corners at all." },
    { who: 'karl', cam: 'house', look: 'house', point: true,
      say: "This is the Lumen Oval. Two storeys in one white elliptical shell, with a terrace running all the way round the ground floor, and a glass roof over the top floor." },
    { who: 'luma', cam: 'two',
      say: "Why an oval, Karl? Most of our viewers live in square houses." },
    { who: 'karl', cam: 'cu',
      say: "Because a house like this is about views. A curved glass wall gives you the whole horizon with no corner post in the way, and every room gets a piece of it." },
    { who: 'luma', cam: 'roof', look: 'roof',
      slide: { kicker: 'Roof light', title: 'A telescoping glass roof', lines: ['Curved glass panels on red ribs', 'They slide along the oval', 'They stack at one end'] },
      say: "Now the part everybody came for. Show them the roof." },
    { who: 'karl', cam: 'roof', look: 'roof', open: 1,
      say: "Watch the top floor. The curved glass panels slide along the oval one behind the other and stack up at the far end, like a telescope closing. The living room is suddenly outside." },
    { who: 'luma', cam: 'cu', mood: 'smile',
      say: "That is beautiful. Is that a mechanism you've already built?" },
    { who: 'karl', cam: 'cu', mood: 'serious',
      slide: { kicker: 'Honest engineering', title: 'Where this idea comes from', lines: ['Built on our LB-1 sliding principle', 'LB-1 panel lifts 8 mm off its seal', 'LB-1 opens in 13.6 seconds', 'The oval version is still a concept'] },
      say: "Not yet, and I want to be straight about that. It grows out of our LB-1 sliding rooflight, where one panel lifts 8 millimetres off its seal and opens in 13.6 seconds. Stacking many curved panels is a new problem, so it stays labelled concept until it's engineered and tested." },
    { who: 'luma', cam: 'two',
      say: "Fair. So what makes it hard?" },
    { who: 'karl', cam: 'cu',
      say: "Every panel has its own seal, and every seal has to stay dry. In a summer thunderstorm the rain sensor has to close the whole roof before the first drops fall, one panel after another, and each one has to lock down tight." },
    { who: 'luma', cam: 'globe', look: 'globe',
      slide: { kicker: 'Grounded in Zimbabwe', title: 'Designing for our climate', lines: ['Afternoon storms: rain sensor closes the roof', 'Strong sun: glass chosen for heat', 'Load-shedding: battery backup + manual override'] },
      say: "And the sun? That's a lot of glass for a Zimbabwean afternoon." },
    { who: 'karl', cam: 'cu',
      say: "It is. So the glass is chosen for heat as well as light, and the white roof ring shades the top of the glass walls. And like all our automated roofs, it runs on battery backup with a manual override, so load-shedding never leaves it open." },
    { who: 'luma', cam: 'house', look: 'house', build: 0, open: 0,
      slide: { kicker: 'Build sequence', title: 'How the Oval goes up', lines: ['Survey and soil test', 'Elliptical plinth with a red band', 'Core and slender columns', 'Middle floor and the roof ring'] },
      say: "Let's build it. Karl, from bare ground." },
    { who: 'karl', cam: 'house', look: 'house', build: 1, point: true,
      say: "Survey and soil test first. Then the elliptical plinth with its red band, and the core and slender columns that carry everything above." },
    { who: 'karl', cam: 'house', look: 'house', build: 3,
      say: "Then the middle floor goes on, and the big white roof ring with the oval opening in the middle. That ring is what makes the building look like it's floating." },
    { who: 'karl', cam: 'house', look: 'house', build: 5,
      slide: { kicker: 'Build sequence', title: 'Closing it in', lines: ['Curved glazing in aluminium frames', 'Terrace glass balustrade', 'Interior fit-out', 'Roof panels, seals and drives'] },
      say: "Curved glass walls in slim aluminium frames on both floors, a glass balustrade round the terrace, and then the fit-out. Aluminium is our home ground." },
    { who: 'karl', cam: 'roof', look: 'roof', build: 7,
      say: "Last come the roof panels and their drives. And nothing leaves the workshop until it's been water-tested on the rig." },
    { who: 'luma', cam: 'screen', look: 'screen',
      slide: { kicker: 'Materials list', title: 'What goes into the Lumen Oval', lines: ['Concrete plinth and core', 'Steel columns and roof ring structure', 'Curved glazing in aluminium frames', 'Sliding glass roof panels on red ribs', 'Seals, drives, rain sensor, battery backup'] },
      ticker: ['Reinforced concrete plinth and core', 'Steel columns, red finish', 'White roof ring structure', 'Curved glazing, aluminium frames', 'Glass terrace balustrade', 'Curved glass roof panels on red ribs', 'Panel drives and seals', 'Rain sensor + controller', 'Battery backup + manual override', 'Waterproofing and flashings'],
      say: "Here's the materials list on screen, for everyone taking notes. Full quantities come after the structural design." },
    { who: 'luma', cam: 'two',
      say: "Last one from me. Where would you actually build this?" },
    { who: 'karl', cam: 'cu', mood: 'smile',
      say: "Anywhere with a view worth opening the roof for. Send me your site on Instagram and we'll talk about what it would take." },
    { who: 'luma', cam: 'wide', mood: 'smile',
      say: "That's the Lumen Oval. Stay with us, the Atlas is already spinning towards the next city." }
  ]
}, {
  /* ================= EPISODE 3 — Rotunda Fan-Roof House · Masvingo ================= */
  id: 'ep3-rotunda-fan', no: 3,
  title: 'The Rotunda Fan',
  subtitle: 'Episode 3 · Masvingo · A round house with a roof that folds like a fan',
  concept: 'rotunda-fan-house', city: 'masvingo',
  lines: [
    { who: 'luma', cam: 'wide', build: 7, open: 0, mood: 'smile', look: 'globe',
      slide: { kicker: 'Episode 3 · Masvingo', title: 'The Rotunda Fan', lines: ['A round glass drum', 'White stone buttresses', 'A roof of glass wedges'] },
      say: "Good evening from the studio. Tonight the Atlas lands in Masvingo, near the ruins of Great Zimbabwe, and our house is perfectly round." },
    { who: 'karl', cam: 'house', look: 'house', point: true,
      say: "This is the Rotunda Fan-Roof House. A round glass drum standing between white stone buttresses, with a red steel ring round the top." },
    { who: 'luma', cam: 'two',
      say: "Round houses feel very at home in Zimbabwe." },
    { who: 'karl', cam: 'cu', mood: 'smile',
      slide: { kicker: 'Heritage', title: 'Why round', lines: ['The rondavel: a traditional round house', 'Great Zimbabwe: curved stone walls', 'A circle has no dark corners'] },
      say: "They do. The rondavel is one of our oldest house forms, and Great Zimbabwe is famous for its stone walls. A circle also has no dark corners, so light from the middle reaches everywhere." },
    { who: 'luma', cam: 'roof', look: 'roof',
      slide: { kicker: 'Roof light', title: 'A fan of glass wedges', lines: ['Eight wedge-shaped glass panels', 'One central pivot', 'They swing round and stack'] },
      say: "And the roof. I've been waiting for this one." },
    { who: 'karl', cam: 'roof', look: 'roof', open: 1,
      say: "The roof is eight glass wedges on one central pivot. Watch. They lift, swing round the centre and stack on top of each other, like a hand fan closing, and half the sky opens up." },
    { who: 'luma', cam: 'cu', mood: 'smile',
      say: "That's hypnotic. How much force does it take?" },
    { who: 'karl', cam: 'cu', mood: 'serious',
      say: "Honest answer: we don't have figures for this one yet. It's a concept mechanism. Every wedge has to be sealed against its neighbours when it's closed, and that pivot carries all of them, so it has to be designed and tested before anyone quotes a number." },
    { who: 'luma', cam: 'two',
      say: "I like that you say that on air." },
    { who: 'karl', cam: 'cu',
      say: "It's the rule on this channel. Rendered, specified, checked, proven. This one is rendered. The rest comes before anyone builds it." },
    { who: 'luma', cam: 'globe', look: 'globe',
      slide: { kicker: 'Grounded in Zimbabwe', title: 'A glass drum in our sun', lines: ['Glass chosen for heat as well as light', 'Stone buttresses shade the walls', 'Rain sensor closes the fan in a storm'] },
      say: "A round glass wall in the Masvingo sun, though. How does it stay cool?" },
    { who: 'karl', cam: 'cu',
      say: "The glass is chosen for heat, the stone buttresses throw shade across the curve, and the roof ring overhangs the top of the glass. And when a storm comes over, the rain sensor closes the fan." },
    { who: 'luma', cam: 'house', look: 'house', build: 0, open: 0,
      slide: { kicker: 'Build sequence', title: 'How the Rotunda goes up', lines: ['Survey and soil test', 'Round plinth', 'Stone buttresses', 'Floor and roof ring'] },
      say: "Let's build it from the ground." },
    { who: 'karl', cam: 'house', look: 'house', build: 1, point: true,
      say: "Soil test, then the round plinth, then the six stone buttresses that hold the roof ring up." },
    { who: 'karl', cam: 'house', look: 'house', build: 3,
      say: "The floor goes down, and the roof ring is lifted on top with its red steel rim." },
    { who: 'karl', cam: 'house', look: 'house', build: 5,
      slide: { kicker: 'Build sequence', title: 'Closing it in', lines: ['Curved glass wall in aluminium frames', 'Interior: round sofa, trees, kitchen', 'The fan roof and its pivot', 'Water test before handover'] },
      say: "Then the curved glass wall in aluminium frames all the way round, and the interior, with that round sofa in the middle." },
    { who: 'karl', cam: 'roof', look: 'roof', build: 7,
      say: "And last, the fan roof on its pivot. Water-tested on the rig before it goes anywhere near a client." },
    { who: 'luma', cam: 'screen', look: 'screen',
      slide: { kicker: 'Materials list', title: 'What goes into the Rotunda', lines: ['Concrete plinth', 'White stone buttresses', 'Steel ring beam, red finish', 'Curved glazing in aluminium frames', 'Glass roof wedges, pivot, seals'] },
      ticker: ['Reinforced concrete plinth', 'White stone buttresses', 'Steel ring beam, red finish', 'Curved glazing, aluminium frames', 'Glass roof wedges in red frames', 'Central pivot and drive', 'Seals between wedges', 'Rain sensor + controller', 'Battery backup + manual override'],
      say: "Here's what goes into it, on screen now. Quantities follow the structural design." },
    { who: 'luma', cam: 'wide', mood: 'smile',
      say: "The Rotunda Fan. Tell us in the comments: would you live in a round house?" },
    { who: 'karl', cam: 'wide', mood: 'smile',
      say: "I would. Stay with us." }
  ]
}, {
  /* ================= EPISODE 4 — Origami Crown Villa · Harare ================= */
  id: 'ep4-origami-crown', no: 4,
  title: 'The Origami Crown',
  subtitle: 'Episode 4 · Harare · Eight glass petals over a stair core',
  concept: 'origami-crown-villa', city: 'harare',
  lines: [
    { who: 'luma', cam: 'wide', build: 7, open: 0, mood: 'smile',
      slide: { kicker: 'Episode 4 · Harare', title: 'The Origami Crown', lines: ['Two white boxes on red columns', 'A glazed stair core', 'A roof that opens like a flower'] },
      say: "Welcome back. We're home in Harare tonight, and this house wears a crown." },
    { who: 'karl', cam: 'house', look: 'house', point: true,
      say: "The Origami Crown Villa. Two white boxes sitting on red steel columns, with a glass stair core between them and a covered terrace underneath." },
    { who: 'luma', cam: 'two',
      say: "Where's the crown?" },
    { who: 'karl', cam: 'roof', look: 'roof', open: 1,
      slide: { kicker: 'Roof light', title: 'Eight folding petals', lines: ['Eight triangular glass petals', 'Hinged round an octagonal opening', 'Closed: a low glass pyramid', 'Open: a crown'] },
      say: "Right on top of the stair core. Closed, it's a low glass pyramid. Open it, and eight triangular petals fold out and up like a flower, and daylight drops straight down the stairwell." },
    { who: 'luma', cam: 'cu', mood: 'smile',
      say: "That is the Iron Man reveal, Karl." },
    { who: 'karl', cam: 'cu', mood: 'smile',
      say: "That's the idea. A roof light should feel like an event, not a ventilation feature." },
    { who: 'luma', cam: 'two',
      say: "Why over the stairs, and not the living room?" },
    { who: 'karl', cam: 'cu',
      say: "Because the stair core is the middle of the house. Light that comes in there spills sideways into both boxes and down to the ground floor. One opening lights the whole plan." },
    { who: 'luma', cam: 'cu',
      say: "Eight petals means a lot of joints, though." },
    { who: 'karl', cam: 'cu', mood: 'serious',
      slide: { kicker: 'Honest engineering', title: 'Eight petals, sixteen seals', lines: ['Every petal edge must seal', 'Water test is critical', 'Concept mechanism: no figures yet'] },
      say: "Exactly, and that's the hard part. Every edge between two petals has to seal when it closes, so the water test on the rig matters more here than anywhere. It's a concept mechanism, so we're not quoting any numbers for it yet." },
    { who: 'luma', cam: 'globe', look: 'globe',
      slide: { kicker: 'Grounded in Zimbabwe', title: 'Built for Harare', lines: ['Rain sensor closes the crown', 'Battery backup + manual override', 'Steel and concrete at ground level', 'Soil test sets the footings'] },
      say: "What about Harare specifically?" },
    { who: 'karl', cam: 'cu',
      say: "Rain sensor to close the crown in the afternoon storms, battery backup for load-shedding, steel and concrete at ground level because termites eat timber, and a soil test, because parts of Harare sit on clay that swells in the rains." },
    { who: 'luma', cam: 'house', look: 'house', build: 0, open: 0,
      slide: { kicker: 'Build sequence', title: 'How the Crown goes up', lines: ['Survey and soil test', 'Podium and steps', 'Red steel columns', 'First floor slab'] },
      say: "Build it for us." },
    { who: 'karl', cam: 'house', look: 'house', build: 1, point: true,
      say: "Podium and steps first, then the red steel columns and the stair core." },
    { who: 'karl', cam: 'house', look: 'house', build: 3,
      say: "The first floor slab goes on, then the two white boxes and the bridge at the back that ties them together. The octagonal kerb sits ready on top of the core." },
    { who: 'karl', cam: 'house', look: 'house', build: 5,
      slide: { kicker: 'Build sequence', title: 'Closing it in', lines: ['Ground floor glass box', 'Framed windows upstairs', 'Terrace, fire table, planters', 'The crown and its hinges'] },
      say: "Then the glass box on the ground floor, the framed windows upstairs, and the terrace with its fire table and planters." },
    { who: 'karl', cam: 'roof', look: 'roof', build: 7,
      say: "And finally the crown itself, petal by petal, then the water test." },
    { who: 'luma', cam: 'screen', look: 'screen',
      slide: { kicker: 'Materials list', title: 'What goes into the Crown', lines: ['Concrete podium and slabs', 'Steel columns, red finish', 'Rendered upper boxes', 'Glazing in aluminium frames', 'Glass petals, hinges, seals, drives'] },
      ticker: ['Reinforced concrete podium and slabs', 'Steel columns, red finish', 'Rendered masonry upper boxes', 'Glazing in aluminium frames', 'Octagonal roof kerb', 'Eight glass petals in red frames', 'Petal hinges, seals and drives', 'Rain sensor + controller', 'Battery backup + manual override'],
      say: "The materials list is up on screen now." },
    { who: 'luma', cam: 'wide', mood: 'smile',
      say: "The Origami Crown. Karl, one word for it." },
    { who: 'karl', cam: 'wide', mood: 'smile',
      say: "Theatre. Stay with us." }
  ]
}, {
  /* ================= EPISODE 5 — Stone Arcade House · Bulawayo ================= */
  id: 'ep5-stone-arcade', no: 5,
  title: 'The Stone Arcade',
  subtitle: 'Episode 5 · Bulawayo · Dry stone below, glass above',
  concept: 'stone-arcade-house', city: 'bulawayo',
  lines: [
    { who: 'luma', cam: 'wide', build: 7, open: 0, mood: 'smile', look: 'globe',
      slide: { kicker: 'Episode 5 · Bulawayo', title: 'The Stone Arcade', lines: ['A dry-stone ground floor of arches', 'A white glass-walled floor above', 'A bi-parting roof light'] },
      say: "Welcome to the studio. The Atlas has taken us to Bulawayo, not far from the granite of the Matobo Hills, and tonight's house is built on stone." },
    { who: 'karl', cam: 'house', look: 'house', point: true,
      say: "The Stone Arcade House. A ground floor of stone walls with arched openings round a courtyard, and a light white floor with full-height glass sitting on top." },
    { who: 'luma', cam: 'two',
      say: "It looks old and new at the same time." },
    { who: 'karl', cam: 'cu', mood: 'smile',
      slide: { kicker: 'Heritage', title: 'Dry-stone walling', lines: ['Great Zimbabwe: granite laid without mortar', 'Kopjes: granite hills across the country', 'Heavy below, light above'] },
      say: "That's the point. The walls of Great Zimbabwe were built of granite blocks laid without mortar, and granite hills are all over this country. So the heavy part is stone, and the light part floats above it." },
    { who: 'luma', cam: 'roof', look: 'roof',
      say: "And up on the roof?" },
    { who: 'karl', cam: 'roof', look: 'roof', open: 1,
      slide: { kicker: 'Roof light', title: 'Bi-parting hinged roof light', lines: ['Two glass leaves in red frames', 'Lift apart from the centre', 'Benchmark aperture 1.5 × 2.0 m'] },
      say: "Our bi-parting roof light. Two glass leaves in red frames lift apart from the centre and open the upper floor to the sky. This is the same family as the Glass Cube from episode one." },
    { who: 'luma', cam: 'cu',
      say: "So this one has real numbers." },
    { who: 'karl', cam: 'cu',
      slide: { kicker: 'From the LB-1 engineering file', title: 'Bi-parting benchmark', lines: ['Benchmark aperture: 1.5 × 2.0 m', 'Lift: 555 newtons per actuator', 'Wind hold: 1,544 newtons per actuator'] },
      say: "On our benchmark opening of 1.5 by 2 metres, yes. Each actuator lifts with 555 newtons and holds 1,544 newtons against the wind. This house would get its own sizing after a survey." },
    { who: 'luma', cam: 'globe', look: 'globe',
      slide: { kicker: 'Grounded in Zimbabwe', title: 'Stone in our climate', lines: ['Thick stone walls help keep rooms cool', 'Stone and concrete: no termite food', 'Rain sensor + battery backup on the roof'] },
      say: "Why does stone make sense in Bulawayo?" },
    { who: 'karl', cam: 'cu',
      say: "Thick stone walls help keep the ground floor cool through the hot part of the day. Termites can't eat them. And upstairs the roof light closes on its rain sensor, with battery backup for load-shedding." },
    { who: 'luma', cam: 'house', look: 'house', build: 0, open: 0,
      slide: { kicker: 'Build sequence', title: 'How the Arcade goes up', lines: ['Survey and soil test', 'Courtyard paving and low wall', 'Stone walls and arches', 'Upper floor slab'] },
      say: "Let's watch it go up." },
    { who: 'karl', cam: 'house', look: 'house', build: 1, point: true,
      say: "Soil test, the courtyard paving and its low stone wall, and then the main stone walls with their arches, course by course." },
    { who: 'karl', cam: 'house', look: 'house', build: 3,
      say: "The white upper floor slab lands on the stone with a thin red line between old and new, then the roof and its parapet go on." },
    { who: 'karl', cam: 'house', look: 'house', build: 5,
      slide: { kicker: 'Build sequence', title: 'Closing it in', lines: ['Full-height glazing, black frames', 'Balcony railing', 'Courtyard tree and loungers', 'Roof light and water test'] },
      say: "Full-height glass in black frames upstairs, the balcony railing, and the courtyard with its tree." },
    { who: 'karl', cam: 'roof', look: 'roof', build: 7,
      say: "Roof light last, water-tested on the rig first." },
    { who: 'luma', cam: 'screen', look: 'screen',
      slide: { kicker: 'Materials list', title: 'What goes into the Arcade', lines: ['Dry-stone walls, stone paving', 'Concrete upper slab and roof', 'Full-height glazing, black frames', 'Bi-parting roof light, actuators, seals'] },
      ticker: ['Local stone for walls and paving', 'Concrete upper floor slab and roof', 'White render', 'Full-height glazing, black aluminium frames', 'Steel balcony railing', 'Bi-parting roof light, red frames', '2 actuators · 555 N lift · 1,544 N wind hold each', 'Rain sensor + battery backup'],
      say: "Materials on screen now." },
    { who: 'luma', cam: 'wide', mood: 'smile',
      say: "The Stone Arcade. Bulawayo, tell us if you'd build in stone." },
    { who: 'karl', cam: 'wide', mood: 'smile',
      say: "And send us your walls. Stay with us." }
  ]
}, {
  /* ================= EPISODE 6 — Granite Plinth Tower · Mutare ================= */
  id: 'ep6-granite-tower', no: 6,
  title: 'The Granite Tower',
  subtitle: 'Episode 6 · Mutare · Floors that float over a granite base',
  concept: 'granite-plinth-tower', city: 'mutare',
  lines: [
    { who: 'luma', cam: 'wide', build: 7, open: 0, mood: 'smile', look: 'globe',
      slide: { kicker: 'Episode 6 · Mutare', title: 'The Granite Tower', lines: ['A black granite plinth', 'Cantilevered concrete floors', 'Slender red steel columns'] },
      say: "Good evening. The Atlas has flown east to Mutare, close to the Eastern Highlands, and tonight's house is the tallest one we've had on stage." },
    { who: 'karl', cam: 'house', look: 'house', point: true,
      say: "The Granite Plinth Tower. A black granite base with a stair cut into it, and concrete floors that reach out past the walls on slender red steel columns." },
    { who: 'luma', cam: 'two',
      say: "Those floors look like they're hanging in the air." },
    { who: 'karl', cam: 'cu', mood: 'serious',
      slide: { kicker: 'Honest engineering', title: 'Cantilevers', lines: ['Floors reach past their supports', 'Sized by a registered engineer', 'Checked, not assumed'] },
      say: "That's a cantilever, and it's where the real engineering is. How far those slabs can reach, and how thick they are, is set by a registered structural engineer. We don't guess that on air." },
    { who: 'luma', cam: 'roof', look: 'roof',
      say: "And at the very top?" },
    { who: 'karl', cam: 'roof', look: 'roof', open: 1,
      say: "A bi-parting pair of glass leaves on struts. They lift apart from the centre and open the top floor to the sky." },
    { who: 'luma', cam: 'cu',
      say: "Same family as the Glass Cube?" },
    { who: 'karl', cam: 'cu',
      slide: { kicker: 'From the LB-1 engineering file', title: 'Bi-parting benchmark', lines: ['Benchmark aperture: 1.5 × 2.0 m', 'Lift: 555 newtons per actuator', 'Wind hold: 1,544 newtons per actuator', 'Glass: 10.38 heat-strengthened laminated'] },
      say: "Same family. On the benchmark opening each actuator lifts with 555 newtons and holds 1,544 against the wind, with 10.38 heat-strengthened laminated glass. Up this high the wind hold matters more, so it would be checked for this exact site." },
    { who: 'luma', cam: 'globe', look: 'globe',
      slide: { kicker: 'Grounded in Zimbabwe', title: 'A hillside house', lines: ['Plinth set into the slope', 'Drainage around the base', 'Rain sensor + battery backup', 'Steel protected against corrosion'] },
      say: "Why does this suit Mutare?" },
    { who: 'karl', cam: 'cu',
      say: "It's a hillside house. The granite plinth sits into the slope, the floors step out for the view, and water has to be led away round the base in the rains. Up top, the rain sensor and battery backup do their usual job." },
    { who: 'luma', cam: 'house', look: 'house', build: 0, open: 0,
      slide: { kicker: 'Build sequence', title: 'How the Tower goes up', lines: ['Survey and soil test', 'Granite plinth and stair', 'Red steel columns', 'Two cantilevered slabs'] },
      say: "Take us from the ground up." },
    { who: 'karl', cam: 'house', look: 'house', build: 1, point: true,
      say: "Survey and soil test, then the granite plinth and the stair, then the red steel columns, full height." },
    { who: 'karl', cam: 'house', look: 'house', build: 3,
      say: "The two concrete slabs go on, then the concrete box on top with its slot windows, and the roof around the opening." },
    { who: 'karl', cam: 'house', look: 'house', build: 5,
      slide: { kicker: 'Build sequence', title: 'Closing it in', lines: ['Glazing on both floors', 'Glass balustrades on the slab edges', 'Interior fit-out', 'Roof light and water test'] },
      say: "Glass walls on both floors, glass balustrades along the slab edges, and the fit-out." },
    { who: 'karl', cam: 'roof', look: 'roof', build: 7,
      say: "And the roof light, water-tested on the rig before handover." },
    { who: 'luma', cam: 'screen', look: 'screen',
      slide: { kicker: 'Materials list', title: 'What goes into the Tower', lines: ['Granite-clad plinth', 'Concrete slabs and top box', 'Steel columns, red finish', 'Glazing and glass balustrades', 'Bi-parting roof light on struts'] },
      ticker: ['Granite-clad concrete plinth and stair', 'Reinforced concrete cantilevered slabs', 'Steel columns, red finish, corrosion protected', 'Glazing in aluminium frames', 'Glass balustrades', 'Bi-parting roof light on struts', '2 actuators · 555 N lift · 1,544 N wind hold each', 'Drainage round the base', 'Rain sensor + battery backup'],
      say: "Here's the materials list." },
    { who: 'luma', cam: 'two',
      say: "Six houses, six roofs. Which is your favourite, Karl?" },
    { who: 'karl', cam: 'cu', mood: 'smile',
      say: "Whichever one somebody asks me to build first. Message me on Instagram." },
    { who: 'luma', cam: 'wide', mood: 'smile',
      say: "That's the whole collection. Stay with us, the studio keeps going." }
  ]
}];
