/* KARLCON Studio — Season 2: the Zimbabwean Heritage Studio Series.
   Ten episodes, one concept each, in the order of the series sheet. Same cue format and house
   rules as Season 1 (see episodes.js): engineering numbers only from the LB-1 engineering file,
   every new mechanism called a concept until it is designed, tested and built.
   Episodes 11–16, From Stand to Keys, are in episodes-s2-build.js.
   Play with /studio?season=2 (and &ep=N), or `node render.mjs --season 2 --ep all`. */
(() => {
  const BUILD = (name, steps) => ({ kicker: 'Build sequence', title: `How the ${name} goes up`, lines: steps });
  const CLOSE = { kicker: 'Build sequence', title: 'Closing it in', lines: ['Glazing in aluminium frames', 'Interior fit-out', 'Roof light kerb, leaves and actuators', 'Water test before handover'] };
  const CLIMATE = (extra) => ({ kicker: 'Grounded in Zimbabwe', title: 'Designing for our climate', lines: ['Summer storms: rain sensor closes the roof', 'Power cuts: battery backup + manual override', ...extra] });
  const HONEST = { kicker: 'Honest engineering', title: 'What is proven, what is concept', lines: ['Proven on LB-1: 555 N lift, 1,544 N wind hold per actuator', 'Glass: 10.38 heat-strengthened laminated', 'This roof: a concept until designed and tested'] };
  const next = (title, city) => ({ kicker: 'Next episode', title, lines: [city, 'Follow @karlcon_lumen_builds_zw'] });

  window.KC_EPISODES_S2 = [{
    /* ================= S2 EPISODE 1 — KARLCON Rondavel · Mutare ================= */
    id: 's2e1-rondavel', no: 1, season: 2,
    title: 'The KARLCON Rondavel',
    subtitle: 'Season 2 · Episode 1 · Mutare · Modern tradition, redefined',
    concept: 'rondavel-concept', city: 'mutare',
    lines: [
      { who: 'luma', cam: 'wide', build: 7, open: 0, mood: 'smile', look: 'globe',
        slide: { kicker: 'Season 2 · The Heritage Studio Series', title: 'The KARLCON Rondavel', lines: ['A round white drum', 'A faceted conical roof', 'An automated roof light at the apex'] },
        say: "Welcome to season two of KARLCON Studios, the Heritage Studio Series. Ten houses, each one rooted in Zimbabwe. We start in Mutare, with the oldest shape we know." },
      { who: 'karl', cam: 'cu', mood: 'smile',
        say: "Good evening. Karl from Lumen Builds, in the new KARLCON Elite Retreats hoodie. New season, new uniform." },
      { who: 'karl', cam: 'house', look: 'house', point: true,
        say: "This is the KARLCON Rondavel. A round white drum, a wide conical roof in flat white panels, and right at the top, where the thatch used to meet, a roof light." },
      { who: 'luma', cam: 'two',
        say: "Karl, every grandmother's homestead has a rondavel. Why rebuild it?" },
      { who: 'karl', cam: 'cu',
        slide: { kicker: 'Heritage', title: 'Why the rondavel still works', lines: ['Round walls: no dark corners', 'A tall cone lets hot air rise', 'A form everyone here recognises'] },
        say: "Because it still works. A round room has no dark corners, and a tall cone lets the hot air rise away from you. We kept the shape and changed the materials, render and panels instead of mud and thatch." },
      { who: 'luma', cam: 'roof', look: 'roof',
        slide: { kicker: 'Roof light', title: 'A butterfly light at the apex', lines: ['Two glass leaves on a square kerb', 'Hinged on the centre line', 'They open into a V'] },
        say: "And the apex. In the old rondavel that was just smoke and thatch. Show them." },
      { who: 'karl', cam: 'roof', look: 'roof', open: 1,
        say: "Two glass leaves sit on a square kerb at the top of the cone. Watch. They hinge on the centre line and open into a V, and daylight drops straight down the middle of the room." },
      { who: 'luma', cam: 'cu', mood: 'smile',
        say: "Like the sun finding its way in through the top of the hut. What lifts them?" },
      { who: 'karl', cam: 'cu', mood: 'serious', slide: HONEST,
        say: "The same actuator family we proved on our LB-1 roof, where each one lifts with 555 newtons and holds 1,544 newtons against the wind. On this cone it's a concept. The leaves are a different shape, so the engineer sizes it before we quote anything." },
      { who: 'luma', cam: 'globe', look: 'globe', slide: CLIMATE(['Eastern Highlands rain: a wide eave', 'White roof: reflects the sun']),
        say: "Mutare gets proper rain from the highlands. What changes?" },
      { who: 'karl', cam: 'cu',
        say: "A wide eave keeps the rain off the walls, a rain sensor closes the light before the first drops, and the white roof reflects the sun. If the power goes, battery backup and a manual override." },
      { who: 'luma', cam: 'house', look: 'house', build: 0, open: 0,
        slide: BUILD('Rondavel', ['Survey and soil test', 'Round slab and plinth', 'Columns round the drum', 'Wall, eave and cone']),
        say: "Let's build it. Karl, from bare ground." },
      { who: 'karl', cam: 'house', look: 'house', build: 1, point: true,
        say: "Soil test, then the round slab and plinth, then the columns that carry the roof, all the way round the drum." },
      { who: 'karl', cam: 'house', look: 'house', build: 3,
        say: "The floor goes in, the drum wall closes round it, and the cone goes on in flat white panels, with a thin red line under the eave." },
      { who: 'karl', cam: 'house', look: 'house', build: 5, slide: CLOSE,
        say: "A glazed door on the far side, and the interior under the apex." },
      { who: 'karl', cam: 'roof', look: 'roof', build: 7,
        say: "Last, the kerb and the two leaves, water-tested on the rig before handover." },
      { who: 'luma', cam: 'screen', look: 'screen',
        slide: { kicker: 'Materials list', title: 'What goes into the Rondavel', lines: ['Concrete slab and plinth', 'Rendered masonry drum', 'Steel roof frame, white panels', 'Laminated roof light, seals, actuators', 'Rain sensor, battery backup'] },
        ticker: ['Concrete slab and plinth', 'Rendered masonry drum wall', 'Steel roof frame', 'White roof panels', 'Red eave trim', 'Laminated roof light', 'Seals and actuators', 'Rain sensor + battery backup'],
        say: "Here's what goes into it. Quantities follow the structural design." },
      { who: 'luma', cam: 'two',
        say: "Would you put this next to a traditional homestead?" },
      { who: 'karl', cam: 'cu', mood: 'smile',
        say: "That's exactly where it belongs. Same circle, same cone, one new window to the sky." },
      { who: 'luma', cam: 'wide', open: 1, mood: 'smile', slide: next('The Lumen Builds Curved Pavilion', 'Harare'),
        say: "That's the KARLCON Rondavel. Next time, a house with no straight walls at all. I'm Luma." },
      { who: 'karl', cam: 'wide', mood: 'smile',
        say: "And I'm Karl. See you next episode." }
    ]
  }, {
    /* ================= S2 EPISODE 2 — Lumen Builds Curved Pavilion · Harare ================= */
    id: 's2e2-curved-pavilion', no: 2, season: 2,
    title: 'The Curved Pavilion',
    subtitle: 'Season 2 · Episode 2 · Harare · A white stone shell you can drive into',
    concept: 'lumen-curved-pavilion', city: 'harare',
    lines: [
      { who: 'luma', cam: 'wide', build: 7, open: 0, mood: 'smile', look: 'globe',
        slide: { kicker: 'Season 2 · Episode 2 · Harare', title: 'The Lumen Builds Curved Pavilion', lines: ['A free-form white stone shell', 'Red fins and a drive-in court', 'A butterfly roof light at the crest'] },
        say: "Welcome back to the Heritage Studio Series. We're in Harare tonight, and this house doesn't have a single straight wall." },
      { who: 'karl', cam: 'house', look: 'house', point: true,
        say: "This is our own signature piece, the Lumen Builds Curved Pavilion. Walls of white coursed stone that swing in and out, red steel fins standing proud of the stone, and a thick white roof that follows every curve." },
      { who: 'luma', cam: 'two',
        say: "And there's a car parked inside the house." },
      { who: 'karl', cam: 'cu', mood: 'smile',
        say: "That's the drive-in court. The front of the shell pinches in and lifts, so you drive under the roof, out of the sun and out of the rain, straight to the front door." },
      { who: 'luma', cam: 'cu',
        slide: { kicker: 'Heritage', title: 'Stone that curves', lines: ['Great Zimbabwe: walls that curve with the land', 'Coursed stone, laid in rows', 'Here: a white stone shell'] },
        say: "Curved stone walls. That sounds very Zimbabwean." },
      { who: 'karl', cam: 'cu',
        say: "It is. The great walls at Great Zimbabwe curve with the land, course after course of stone. We took that idea, white stone in long rows, and wrapped a house in it." },
      { who: 'luma', cam: 'roof', look: 'roof',
        slide: { kicker: 'Roof light', title: 'A butterfly light at the crest', lines: ['Two glass leaves', 'Hinged on the centre line', 'They open into a V over the living room'] },
        say: "Now the roof, please." },
      { who: 'karl', cam: 'roof', look: 'roof', open: 1,
        say: "Two glass leaves at the crest of the roof. They hinge in the middle and open into a V, like a butterfly lifting its wings, right over the living room." },
      { who: 'luma', cam: 'cu', mood: 'smile',
        say: "The butterfly is becoming this season's signature. Is it built?" },
      { who: 'karl', cam: 'cu', mood: 'serious', slide: HONEST,
        say: "Not yet. What's proven is the actuator family from our LB-1 roof, 555 newtons of lift and 1,544 newtons of wind hold per actuator, and the laminated glass. This butterfly on a curved roof is a concept until it's engineered and tested." },
      { who: 'luma', cam: 'globe', look: 'globe', slide: CLIMATE(['Stone walls: thermal mass, cool inside', 'Deep roof edge shades the walls']),
        say: "Harare summers. How does a white stone house cope?" },
      { who: 'karl', cam: 'cu',
        say: "Stone walls soak up the heat of the day slowly, so the inside stays cool, and the thick roof edge shades them. Rain sensor on the roof light, battery backup for the power cuts." },
      { who: 'luma', cam: 'house', look: 'house', build: 0, open: 0,
        slide: BUILD('Curved Pavilion', ['Survey and soil test', 'Slab to the curved outline', 'Stone walls and red fins', 'Roof shell and lintel over the court']),
        say: "Let's build it." },
      { who: 'karl', cam: 'house', look: 'house', build: 1, point: true,
        say: "Soil test, then a slab poured to that curved outline. The stone walls go up course by course, the red fins are fixed, and the stone ramp sweeps down on the right." },
      { who: 'karl', cam: 'house', look: 'house', build: 3,
        say: "Then the thick white roof goes on, with the stone lintel arching over the drive-in court." },
      { who: 'karl', cam: 'house', look: 'house', build: 5, slide: CLOSE,
        say: "Glazing inside the court, the interior, and the lighting under the soffit." },
      { who: 'karl', cam: 'roof', look: 'roof', build: 7,
        say: "And the butterfly light at the crest, water-tested before handover." },
      { who: 'luma', cam: 'screen', look: 'screen',
        slide: { kicker: 'Materials list', title: 'What goes into the Curved Pavilion', lines: ['Concrete slab to a curved outline', 'White coursed stone walls', 'Red steel fins and columns', 'Concrete roof shell, white finish', 'Laminated roof light, actuators'] },
        ticker: ['Concrete slab, curved outline', 'White coursed stone', 'Red steel fins and columns', 'Concrete roof shell', 'Glazing in aluminium frames', 'Laminated roof light', 'Seals and actuators', 'Rain sensor + battery backup'],
        say: "Here's the materials list on screen." },
      { who: 'luma', cam: 'wide', open: 1, mood: 'smile', slide: next('The Conical Tower Loft', 'Masvingo'),
        say: "The Curved Pavilion. Next time we head to Masvingo, and a tower that owes a lot to Great Zimbabwe. I'm Luma." },
      { who: 'karl', cam: 'wide', mood: 'smile',
        say: "And I'm Karl. Stay with us." }
    ]
  }, {
    /* ================= S2 EPISODE 3 — Conical Tower Loft · Masvingo ================= */
    id: 's2e3-conical-tower', no: 3, season: 2,
    title: 'The Conical Tower Loft',
    subtitle: 'Season 2 · Episode 3 · Masvingo · Industrial luxury, redefined',
    concept: 'conical-tower-loft', city: 'masvingo',
    lines: [
      { who: 'luma', cam: 'wide', build: 7, open: 0, mood: 'smile', look: 'globe',
        slide: { kicker: 'Season 2 · Episode 3 · Masvingo', title: 'The Conical Tower Loft', lines: ['A tapered white-stone tower', 'A red steel exoskeleton', 'A bi-parting crown on top'] },
        say: "Good evening from the studio. Tonight the Atlas lands in Masvingo, a short drive from Great Zimbabwe, and our house is a tower." },
      { who: 'karl', cam: 'house', look: 'house', point: true,
        say: "The Conical Tower Loft. A white stone tower that narrows as it rises, a band of glass wrapped round the living floor, and a red steel frame standing round the whole thing." },
      { who: 'luma', cam: 'two',
        say: "Karl, anyone who has been to Great Zimbabwe knows that shape." },
      { who: 'karl', cam: 'cu',
        slide: { kicker: 'Heritage', title: 'The Conical Tower', lines: ['Great Zimbabwe, near Masvingo', 'A solid dry-stone tower in the Great Enclosure', 'Built without mortar'] },
        say: "They do. Inside the Great Enclosure there's the Conical Tower, solid dry stone, built without mortar, and still standing. Ours is hollow, it's a home, but it tapers the same way." },
      { who: 'luma', cam: 'cu',
        say: "And the red frame round it?" },
      { who: 'karl', cam: 'cu',
        say: "The exoskeleton. Six red steel legs and three rings. It braces the tower, carries the glass band, and gives you something to hang shading off. The stone does the solid work, the steel does the lifting." },
      { who: 'luma', cam: 'roof', look: 'roof',
        slide: { kicker: 'Roof light', title: 'A bi-parting crown', lines: ['Two glass leaves on the top', 'Hinged on the outer edges', 'They lift apart from the centre'] },
        say: "What's on top of the tower?" },
      { who: 'karl', cam: 'roof', look: 'roof', open: 1,
        say: "The crown. Two glass leaves hinged on the outer edges. They lift apart from the centre, and the light falls all the way down the tower." },
      { who: 'luma', cam: 'cu', mood: 'smile',
        say: "That's our season one roof, on a tower." },
      { who: 'karl', cam: 'cu', mood: 'serious', slide: HONEST,
        say: "Same principle, yes. On LB-1 each actuator lifts with 555 newtons and holds 1,544 newtons against the wind. Up a tower the wind is stronger, so the engineer checks those loads for this height before anyone builds it." },
      { who: 'luma', cam: 'globe', look: 'globe', slide: CLIMATE(['Stone: cool inside in the heat', 'Higher up: stronger wind, checked by the engineer']),
        say: "Masvingo is hot and dry for much of the year." },
      { who: 'karl', cam: 'cu',
        say: "Thick stone keeps the heat out, the glass band is shaded by the frame, and the crown opens at night to let the warm air out the top. When the rains come, the sensor closes it." },
      { who: 'luma', cam: 'house', look: 'house', build: 0, open: 0,
        slide: BUILD('Tower', ['Survey and soil test', 'Round plinth', 'Red steel exoskeleton', 'Stone tower and floors']),
        say: "Let's build the tower." },
      { who: 'karl', cam: 'house', look: 'house', build: 1, point: true,
        say: "Soil test and the round plinth, then the red exoskeleton goes up first, six legs and three rings." },
      { who: 'karl', cam: 'house', look: 'house', build: 3,
        say: "The floors go in, and the stone tower rises inside the frame, narrowing as it goes." },
      { who: 'karl', cam: 'house', look: 'house', build: 5, slide: CLOSE,
        say: "The glass band round the living floor, then the interior." },
      { who: 'karl', cam: 'roof', look: 'roof', build: 7,
        say: "And the crown on top, water-tested before handover." },
      { who: 'luma', cam: 'screen', look: 'screen',
        slide: { kicker: 'Materials list', title: 'What goes into the Tower', lines: ['Concrete plinth and floors', 'White stone, tapered', 'Red steel exoskeleton', 'Curved glazing band', 'Bi-parting crown, actuators'] },
        ticker: ['Concrete plinth and floors', 'White coursed stone', 'Red steel legs and rings', 'Curved glazing in aluminium frames', 'Bi-parting roof light', '2 actuators · 555 N lift · 1,544 N wind hold each (LB-1)', 'Rain sensor + battery backup'],
        say: "Here's what goes into it." },
      { who: 'luma', cam: 'wide', open: 1, mood: 'smile', slide: next('The Elevated Glass Cube', 'Harare'),
        say: "The Conical Tower Loft. Next time, an old favourite returns to the studio. I'm Luma." },
      { who: 'karl', cam: 'wide', mood: 'smile',
        say: "And I'm Karl. See you then." }
    ]
  }, {
    /* ================= S2 EPISODE 4 — Elevated Glass Cube · Harare ================= */
    id: 's2e4-glass-cube', no: 4, season: 2,
    title: 'The Glass Cube, Revisited',
    subtitle: 'Season 2 · Episode 4 · Harare · The house that floats, one season on',
    concept: 'cantilever-pavilion', city: 'harare',
    lines: [
      { who: 'luma', cam: 'wide', build: 7, open: 0, mood: 'smile', look: 'globe',
        slide: { kicker: 'Season 2 · Episode 4 · Harare', title: 'The Elevated Glass Cube', lines: ['A glazed box on four red columns', 'Red stools underneath', 'The bi-parting roof light'] },
        say: "Welcome back. Tonight an old friend is back on stage: the Elevated Glass Cube, the house that started this channel." },
      { who: 'karl', cam: 'house', look: 'house', point: true,
        say: "A white box with a full glass front, lifted on four red steel columns, and the roof light that opens right over the lounge." },
      { who: 'luma', cam: 'two',
        say: "So why bring it back in a heritage season?" },
      { who: 'karl', cam: 'cu',
        slide: { kicker: 'Heritage', title: 'Lifting the house', lines: ['Granaries raised off the ground', 'Air underneath, dry above', 'The same idea, in steel and glass'] },
        say: "Because lifting a store off the ground is an old idea here. Raised granaries keep the grain dry and away from pests. We lift the whole living room, for the view, the shade underneath, and to keep it above the storm water." },
      { who: 'luma', cam: 'roof', look: 'roof',
        slide: { kicker: 'Roof light', title: 'Bi-parting hinged roof light', lines: ['Two glass leaves lift apart', 'Paired actuators', 'Benchmark aperture 1.5 × 2.0 m'] },
        say: "And the roof, one more time." },
      { who: 'karl', cam: 'roof', look: 'roof', open: 1,
        say: "Two glass leaves lift apart from the centre on paired actuators, and the lounge opens to the sky." },
      { who: 'luma', cam: 'cu', mood: 'smile',
        say: "Remind everyone of the numbers." },
      { who: 'karl', cam: 'cu',
        slide: { kicker: 'From the LB-1 engineering file', title: 'The numbers behind the reveal', lines: ['Benchmark aperture: 1.5 × 2.0 m', 'Lift: 555 newtons per actuator', 'Wind hold: 1,544 newtons per actuator', 'Glass: 10.38 heat-strengthened laminated'] },
        say: "On our benchmark opening of one and a half by two metres, 555 newtons of lift per actuator, 1,544 newtons of hold against the wind, and ten point three eight heat-strengthened laminated glass." },
      { who: 'luma', cam: 'globe', look: 'globe', slide: CLIMATE(['Glass chosen for heat, not just looks', 'Steel and concrete: termites eat neither']),
        say: "And the Harare sun on all that glass?" },
      { who: 'karl', cam: 'cu',
        say: "The glass is chosen for heat, not just looks, and the planner shows how much heat each glass lets in before we size anything. Steel and concrete at ground level, because termites eat neither." },
      { who: 'luma', cam: 'house', look: 'house', build: 0, open: 0,
        slide: BUILD('Glass Cube', ['Survey and soil test', 'Pad footings, hold-down bolts', 'Red columns, grouted', 'Floor deck, walls, roof']),
        say: "Build it for the new viewers, Karl." },
      { who: 'karl', cam: 'house', look: 'house', build: 1, point: true,
        say: "Soil test, four pad footings with hold-down bolts, and the red columns grouted to the bolts." },
      { who: 'karl', cam: 'house', look: 'house', build: 3,
        say: "The floor deck is lifted into place, then the walls and the roof frame." },
      { who: 'karl', cam: 'house', look: 'house', build: 5, slide: CLOSE,
        say: "Full-height glazing in dark aluminium frames, and the interior." },
      { who: 'karl', cam: 'roof', look: 'roof', build: 7,
        say: "Then the roof light, water-tested on the rig." },
      { who: 'luma', cam: 'screen', look: 'screen',
        slide: { kicker: 'Materials list', title: 'What goes into the Glass Cube', lines: ['Concrete footings, bolts, grout', 'Galvanised steel columns, red finish', 'Insulated walls, white render', 'Aluminium-framed glazing', 'Laminated roof light, actuators'] },
        ticker: ['Concrete pad footings, reinforced', 'Hold-down bolts + non-shrink grout', 'Steel columns, red finish', 'Insulated walls, white render', 'Full-height glazing, dark aluminium frames', 'Roof light: 10.38 heat-strengthened laminated glass', '2 actuators · 555 N lift · 1,544 N wind hold each', 'Rain sensor + battery backup'],
        say: "The full list is on screen now." },
      { who: 'luma', cam: 'wide', open: 1, mood: 'smile', slide: next('The Chevron Motif Pavilion', 'Masvingo'),
        say: "The Glass Cube, still floating. Next time, a pattern carved into the walls of Great Zimbabwe. I'm Luma." },
      { who: 'karl', cam: 'wide', mood: 'smile',
        say: "And I'm Karl. See you next episode." }
    ]
  }, {
    /* ================= S2 EPISODE 5 — Chevron Motif Pavilion · Masvingo ================= */
    id: 's2e5-chevron', no: 5, season: 2,
    title: 'The Chevron Motif Pavilion',
    subtitle: 'Season 2 · Episode 5 · Masvingo · Cultural heritage architecture',
    concept: 'chevron-pavilion', city: 'masvingo',
    lines: [
      { who: 'luma', cam: 'wide', build: 7, open: 0, mood: 'smile', look: 'globe',
        slide: { kicker: 'Season 2 · Episode 5 · Masvingo', title: 'The Chevron Motif Pavilion', lines: ['A red steel frame', 'White chevron panels', 'A bi-parting roof light'] },
        say: "Welcome back to the Heritage Studio Series. We're in Masvingo again, and tonight the building wears a pattern." },
      { who: 'karl', cam: 'house', look: 'house', point: true,
        say: "The Chevron Motif Pavilion. A square pavilion in a red steel frame, four bays to a side. Most bays are white panels cut with a chevron pattern, and some are left open to the glass." },
      { who: 'luma', cam: 'two',
        say: "That zigzag. Where does it come from?" },
      { who: 'karl', cam: 'cu',
        slide: { kicker: 'Heritage', title: 'The chevron', lines: ['A chevron band runs along the top of the Great Enclosure wall', 'Great Zimbabwe, near Masvingo', 'Here: cut into white panels'] },
        say: "From Great Zimbabwe. Along the top of the outer wall of the Great Enclosure there's a band of stones laid in a chevron pattern. We cut that same zigzag into the panels." },
      { who: 'luma', cam: 'cu',
        say: "Is it only decoration?" },
      { who: 'karl', cam: 'cu',
        say: "Mostly, and that's allowed. But the grooves also break up the glare on a white wall, and panels are easy to swap when you want a bay open to the garden instead." },
      { who: 'luma', cam: 'roof', look: 'roof',
        slide: { kicker: 'Roof light', title: 'A large bi-parting light', lines: ['A big opening in the middle of the roof', 'Two leaves lift apart', 'The whole centre of the room opens'] },
        say: "And the roof." },
      { who: 'karl', cam: 'roof', look: 'roof', open: 1,
        say: "A big opening right in the middle of the roof, and two glass leaves that lift apart. The whole centre of the pavilion opens to the sky." },
      { who: 'luma', cam: 'cu', mood: 'smile',
        say: "That's the biggest opening yet." },
      { who: 'karl', cam: 'cu', mood: 'serious', slide: HONEST,
        say: "It is, and that matters. Our proven numbers are for the LB-1 benchmark, one and a half by two metres. A bigger leaf is heavier and catches more wind, so it gets its own sizing. Until then, it's a concept." },
      { who: 'luma', cam: 'globe', look: 'globe', slide: CLIMATE(['Panels shade the walls', 'Open bays let the breeze through']),
        say: "Hot days in Masvingo. How does it stay comfortable?" },
      { who: 'karl', cam: 'cu',
        say: "The solid panels shade most of the walls, the open bays let the breeze through, and warm air leaves through the roof when it's open. Rain sensor and battery backup, as always." },
      { who: 'luma', cam: 'house', look: 'house', build: 0, open: 0,
        slide: BUILD('Chevron Pavilion', ['Survey and soil test', 'Slab and plinth', 'Red steel frame', 'Chevron panels and roof']),
        say: "Let's build it." },
      { who: 'karl', cam: 'house', look: 'house', build: 1, point: true,
        say: "Soil test and the slab, then the red steel frame: posts at every bay, a mid rail, top and bottom beams." },
      { who: 'karl', cam: 'house', look: 'house', build: 3,
        say: "The floor, the chevron panels bay by bay, and the roof slab round the big opening." },
      { who: 'karl', cam: 'house', look: 'house', build: 5, slide: CLOSE,
        say: "Glass in the open bays, then the interior." },
      { who: 'karl', cam: 'roof', look: 'roof', build: 7,
        say: "And the two leaves, water-tested before handover." },
      { who: 'luma', cam: 'screen', look: 'screen',
        slide: { kicker: 'Materials list', title: 'What goes into the Pavilion', lines: ['Concrete slab and plinth', 'Red steel frame', 'White panels, chevron relief', 'Glazing in the open bays', 'Bi-parting roof light, actuators'] },
        ticker: ['Concrete slab and plinth', 'Steel frame, red finish', 'White panels with chevron relief', 'Glazing in aluminium frames', 'Concrete roof slab', 'Bi-parting roof light', 'Seals and actuators', 'Rain sensor + battery backup'],
        say: "Here's the materials list." },
      { who: 'luma', cam: 'wide', open: 1, mood: 'smile', slide: next('The Triple Rondavel Cluster', 'Mutare'),
        say: "The Chevron Motif Pavilion. Next time, three rondavels become one home. I'm Luma." },
      { who: 'karl', cam: 'wide', mood: 'smile',
        say: "And I'm Karl. Stay with us." }
    ]
  }, {
    /* ================= S2 EPISODE 6 — Triple Rondavel Cluster · Mutare ================= */
    id: 's2e6-triple-rondavel', no: 6, season: 2,
    title: 'The Triple Rondavel Cluster',
    subtitle: 'Season 2 · Episode 6 · Mutare · Efficient. Circular. Redefined.',
    concept: 'triple-rondavel-cluster', city: 'mutare',
    lines: [
      { who: 'luma', cam: 'wide', build: 7, open: 0, mood: 'smile', look: 'globe',
        slide: { kicker: 'Season 2 · Episode 6 · Mutare', title: 'The Triple Rondavel Cluster', lines: ['Three round rooms', 'Joined by a folded glass spine', 'A butterfly light over the central cone'] },
        say: "Welcome back. The Atlas is in Mutare again, and tonight one rondavel wasn't enough. We have three." },
      { who: 'karl', cam: 'house', look: 'house', point: true,
        say: "The Triple Rondavel Cluster. A big drum in the middle under a low cone, a flat-roofed drum on each side, and a folded wall of red-framed glass joining them all." },
      { who: 'luma', cam: 'two',
        say: "It looks like a homestead, all under one roof." },
      { who: 'karl', cam: 'cu',
        slide: { kicker: 'Heritage', title: 'The homestead', lines: ['Several round houses round a yard', 'Each with its own job', 'Here: joined by a glass spine'] },
        say: "That's the idea. A traditional homestead is several round houses, each with its own job, around a yard. We kept the separate rooms and joined them with glass, so you never step out in the rain." },
      { who: 'luma', cam: 'cu',
        say: "Why fold the glass instead of running it straight?" },
      { who: 'karl', cam: 'cu',
        say: "A folded wall stands up to the wind better than a flat one, it catches the light at different angles through the day, and it echoes the chevrons we saw last episode." },
      { who: 'luma', cam: 'roof', look: 'roof',
        slide: { kicker: 'Roof light', title: 'A butterfly over the cone', lines: ['Two glass leaves on the central cone', 'Hinged on the centre line', 'They open into a V'] },
        say: "And the roof light is in the middle." },
      { who: 'karl', cam: 'roof', look: 'roof', open: 1,
        say: "On top of the central cone. Two leaves hinge in the middle and open into a V, and the main living room gets daylight straight down the centre." },
      { who: 'luma', cam: 'cu', mood: 'smile',
        say: "Engineering status?" },
      { who: 'karl', cam: 'cu', mood: 'serious', slide: HONEST,
        say: "Proven: the LB-1 actuators, 555 newtons of lift and 1,544 of wind hold each, and the laminated glass. This butterfly on a cone is a concept until it's engineered and tested." },
      { who: 'luma', cam: 'globe', look: 'globe', slide: CLIMATE(['Round rooms: less wall for the sun to heat', 'Glass spine: shaded by the roof edge']),
        say: "Mutare rain and highland mist. Does it cope?" },
      { who: 'karl', cam: 'cu',
        say: "Round rooms have less wall for the sun to heat, the spine's roof shades the glass, and the flat roofs drain to the outside of each drum. The roof light closes itself when the rain starts." },
      { who: 'luma', cam: 'house', look: 'house', build: 0, open: 0,
        slide: BUILD('Cluster', ['Survey and soil test', 'Three round slabs', 'Three drums', 'Cone, flat roofs, spine roof']),
        say: "Let's build it." },
      { who: 'karl', cam: 'house', look: 'house', build: 1, point: true,
        say: "Soil test, three round slabs, then the three drums go up, with the red frame of the glass spine between them." },
      { who: 'karl', cam: 'house', look: 'house', build: 3,
        say: "The floors, the low cone on the middle drum, flat roofs on the side drums, and the roof over the spine." },
      { who: 'karl', cam: 'house', look: 'house', build: 5, slide: CLOSE,
        say: "Glass into the spine and the side drums, then the interior." },
      { who: 'karl', cam: 'roof', look: 'roof', build: 7,
        say: "And the butterfly on the cone, water-tested before handover." },
      { who: 'luma', cam: 'screen', look: 'screen',
        slide: { kicker: 'Materials list', title: 'What goes into the Cluster', lines: ['Three concrete slabs', 'Rendered masonry drums', 'Red steel glazing frame', 'Concrete cone and flat roofs', 'Butterfly roof light, actuators'] },
        ticker: ['Concrete slabs', 'Rendered masonry drums', 'Steel glazing frame, red finish', 'Glazing in aluminium frames', 'Concrete cone and flat roofs', 'Butterfly roof light', 'Seals and actuators', 'Rain sensor + battery backup'],
        say: "The materials list, on screen now." },
      { who: 'luma', cam: 'wide', open: 1, mood: 'smile', slide: next('The Matobo Boulder House', 'Bulawayo'),
        say: "The Triple Rondavel Cluster. Next time we go to the Matobo Hills. I'm Luma." },
      { who: 'karl', cam: 'wide', mood: 'smile',
        say: "And I'm Karl. You'll want to see this one." }
    ]
  }, {
    /* ================= S2 EPISODE 7 — Matobo Boulder House · Bulawayo ================= */
    id: 's2e7-matobo', no: 7, season: 2,
    title: 'The Matobo Boulder House',
    subtitle: 'Season 2 · Episode 7 · Bulawayo · Organic luxury, redefined',
    concept: 'matobo-boulder-house', city: 'bulawayo',
    lines: [
      { who: 'luma', cam: 'wide', build: 7, open: 0, mood: 'smile', look: 'globe',
        slide: { kicker: 'Season 2 · Episode 7 · Bulawayo', title: 'The Matobo Boulder House', lines: ['Granite-form boulders', 'Red-framed glass rooms between them', 'An X-shaped roof light'] },
        say: "Good evening. Tonight the Atlas lands near Bulawayo, and the Matobo Hills. Our house is hiding among the boulders." },
      { who: 'karl', cam: 'house', look: 'house', point: true,
        say: "The Matobo Boulder House. Big rounded boulder forms, and set in between them, three glass rooms in red steel frames, one on the ground and two up on the rocks." },
      { who: 'luma', cam: 'two',
        say: "Anyone from Bulawayo knows those rocks." },
      { who: 'karl', cam: 'cu',
        slide: { kicker: 'Heritage', title: 'The Matobo Hills', lines: ['Granite kopjes and balancing rocks', 'South of Bulawayo', 'A UNESCO World Heritage Site'] },
        say: "Everyone does. The Matobo Hills, south of Bulawayo, granite kopjes and balancing rocks, a World Heritage Site. People have sheltered among those rocks for thousands of years. We wanted rooms that sit in the rocks the same way." },
      { who: 'luma', cam: 'cu',
        say: "So are the boulders real rock?" },
      { who: 'karl', cam: 'cu', mood: 'serious',
        say: "In this concept they're boulder forms: shells shaped like granite, over a structure that carries the glass rooms. On a real kopje site you'd build between the real rocks. That's a site survey decision, not a guess." },
      { who: 'luma', cam: 'roof', look: 'roof',
        slide: { kicker: 'Roof light', title: 'An X-shaped light', lines: ['Two leaves on the top boulder', 'Hinged on the outer edges', 'They swing up and cross in an X'] },
        say: "And on top of the biggest boulder?" },
      { who: 'karl', cam: 'roof', look: 'roof', open: 1,
        say: "Two glass leaves hinged on their outer edges. Watch. They swing up past upright and cross each other, like an X standing on the rock." },
      { who: 'luma', cam: 'cu', mood: 'smile',
        say: "That's the most dramatic one yet." },
      { who: 'karl', cam: 'cu', mood: 'serious', slide: HONEST,
        say: "And the least proven. Our proven numbers are for leaves opening to a normal angle on LB-1. Swinging past upright means the loads change as it moves, so this is a concept until it's engineered and tested." },
      { who: 'luma', cam: 'globe', look: 'globe', slide: CLIMATE(['Granite forms: shade and thermal mass', 'Glass rooms: glass chosen for heat']),
        say: "Matabeleland gets very hot and very dry." },
      { who: 'karl', cam: 'cu',
        say: "The boulders shade the rooms and hold the cool of the night, and the glass is chosen for heat. The roof light opens in the evening to let the heat out." },
      { who: 'luma', cam: 'house', look: 'house', build: 0, open: 0,
        slide: BUILD('Boulder House', ['Site survey among the rocks', 'Ground slab', 'Boulder forms and structure', 'Glass rooms in red frames']),
        say: "Let's build it." },
      { who: 'karl', cam: 'house', look: 'house', build: 1, point: true,
        say: "A proper site survey first, then the ground slab and the boulder forms with the structure inside them." },
      { who: 'karl', cam: 'house', look: 'house', build: 3,
        say: "The red frames of the three glass rooms go in, one at ground level and two up on the rocks." },
      { who: 'karl', cam: 'house', look: 'house', build: 5, slide: CLOSE,
        say: "Glass into the frames, then the interiors." },
      { who: 'karl', cam: 'roof', look: 'roof', build: 7,
        say: "And the X light on the top boulder, water-tested before handover." },
      { who: 'luma', cam: 'screen', look: 'screen',
        slide: { kicker: 'Materials list', title: 'What goes into the Boulder House', lines: ['Concrete slab', 'Boulder forms over a structural frame', 'Red steel room frames', 'Glazing in the rooms', 'X roof light, actuators'] },
        ticker: ['Concrete ground slab', 'Boulder-form shells', 'Structural frame inside the forms', 'Steel room frames, red finish', 'Glazing in aluminium frames', 'X-opening roof light', 'Seals and actuators', 'Rain sensor + battery backup'],
        say: "Here's what goes into it." },
      { who: 'luma', cam: 'wide', open: 1, mood: 'smile', slide: next('The Terraced Hillside Complex', 'Masvingo'),
        say: "The Matobo Boulder House. Next time, stone terraces climbing a hill. I'm Luma." },
      { who: 'karl', cam: 'wide', mood: 'smile',
        say: "And I'm Karl. See you then." }
    ]
  }, {
    /* ================= S2 EPISODE 8 — Terraced Hillside Complex · Masvingo ================= */
    id: 's2e8-terraced', no: 8, season: 2,
    title: 'The Terraced Hillside Complex',
    subtitle: 'Season 2 · Episode 8 · Masvingo · Architectural synthesis, redefined',
    concept: 'terraced-hillside', city: 'masvingo',
    lines: [
      { who: 'luma', cam: 'wide', build: 7, open: 0, mood: 'smile', look: 'globe',
        slide: { kicker: 'Season 2 · Episode 8 · Masvingo', title: 'The Terraced Hillside Complex', lines: ['Dry-stone terraces', 'A cantilevered red glass pavilion', 'A lattice crown on top'] },
        say: "Welcome back to the Heritage Studio Series. We're back near Great Zimbabwe, and tonight the house climbs a hill." },
      { who: 'karl', cam: 'house', look: 'house', point: true,
        say: "The Terraced Hillside Complex. White stone terraces stepping up the slope, a narrow stair cut up the front, and on the top terrace a red steel glass pavilion that reaches out past the edge." },
      { who: 'luma', cam: 'two',
        say: "Terraces up a hill. That's very Great Zimbabwe too." },
      { who: 'karl', cam: 'cu',
        slide: { kicker: 'Heritage', title: 'The Hill Complex', lines: ['The oldest part of Great Zimbabwe', 'Stone walls built into the hilltop', 'Terraces that follow the rock'] },
        say: "It is. The oldest part of Great Zimbabwe is the Hill Complex, stone walls built right into the hilltop, following the rock. Terracing is how you make a steep site useful." },
      { who: 'luma', cam: 'cu',
        say: "And the glass box hanging off the top?" },
      { who: 'karl', cam: 'cu',
        say: "The cantilever. The pavilion sits on the top terrace and a stone pier at the back, and reaches out over the steps. You get the view down the whole hill, and the terraces become the garden." },
      { who: 'luma', cam: 'roof', look: 'roof',
        slide: { kicker: 'Roof light', title: 'A butterfly under a lattice crown', lines: ['A smaller glass room on top', 'A red steel lattice crown', 'Two leaves open into a V inside it'] },
        say: "And the top of the top?" },
      { who: 'karl', cam: 'roof', look: 'roof', open: 1,
        say: "A smaller glass room, then a red steel lattice crown, and inside it two leaves that open into a V. The light comes down through both floors." },
      { who: 'luma', cam: 'cu', mood: 'smile',
        say: "How much of this is proven?" },
      { who: 'karl', cam: 'cu', mood: 'serious', slide: HONEST,
        say: "The actuators and the glass, from LB-1. The cantilever and the crown are concept. A cantilever over steps is exactly the kind of thing the structural engineer designs, not us on television." },
      { who: 'luma', cam: 'globe', look: 'globe', slide: CLIMATE(['Terraces: drainage down the slope', 'Stone: holds the cool of the night']),
        say: "What about the rains on a slope?" },
      { who: 'karl', cam: 'cu',
        say: "Every terrace has to drain, so water steps down the hill instead of through the house. The stone holds the cool of the night, and the rain sensor closes the crown." },
      { who: 'luma', cam: 'house', look: 'house', build: 0, open: 0,
        slide: BUILD('Hillside Complex', ['Site and soil survey', 'Stone terraces and stair', 'Stone pier and red frame', 'Deck, walls, top room']),
        say: "Let's build it." },
      { who: 'karl', cam: 'house', look: 'house', build: 1, point: true,
        say: "The terraces and the stair first, stone course by course. Then the stone pier at the back and the red steel frame of the pavilion." },
      { who: 'karl', cam: 'house', look: 'house', build: 3,
        say: "The deck goes on, reaching out over the steps, then the roof and the frame of the smaller room on top." },
      { who: 'karl', cam: 'house', look: 'house', build: 5, slide: CLOSE,
        say: "Glass on both levels, then the interior." },
      { who: 'karl', cam: 'roof', look: 'roof', build: 7,
        say: "And the lattice crown with its two leaves, water-tested before handover." },
      { who: 'luma', cam: 'screen', look: 'screen',
        slide: { kicker: 'Materials list', title: 'What goes into the Complex', lines: ['Dry-stone terraces with drainage', 'Stone pier', 'Red steel frame, braced', 'Glazing on two levels', 'Lattice crown, butterfly light'] },
        ticker: ['Stone terraces with drainage', 'Stone stair and pier', 'Steel frame, red finish, braced', 'Cantilevered deck', 'Glazing in aluminium frames', 'Red steel lattice crown', 'Butterfly roof light', 'Rain sensor + battery backup'],
        say: "The materials list is on screen." },
      { who: 'luma', cam: 'wide', open: 1, mood: 'smile', slide: next('The Circular Ring Pavilion', 'Bulawayo'),
        say: "The Terraced Hillside Complex. Next time, a roof shaped like a ring. I'm Luma." },
      { who: 'karl', cam: 'wide', mood: 'smile',
        say: "And I'm Karl. Stay with us." }
    ]
  }, {
    /* ================= S2 EPISODE 9 — Circular Ring Pavilion · Bulawayo ================= */
    id: 's2e9-ring', no: 9, season: 2,
    title: 'The Circular Ring Pavilion',
    subtitle: 'Season 2 · Episode 9 · Bulawayo · Final engineering specifications',
    concept: 'studio-ring-stage', city: 'bulawayo',
    lines: [
      { who: 'luma', cam: 'wide', build: 7, open: 0, mood: 'smile', look: 'globe',
        slide: { kicker: 'Season 2 · Episode 9 · Bulawayo', title: 'The Circular Ring Pavilion', lines: ['A white ring roof', 'A glazed drum in red frames', 'Twin roof lights on the rim'] },
        say: "Good evening. The Atlas is back in Bulawayo, and tonight's building is a circle with a hole in the middle." },
      { who: 'karl', cam: 'house', look: 'house', point: true,
        say: "The Circular Ring Pavilion. A thick white ring of a roof floating over a round glass wall in red frames. In the middle, an open courtyard straight up to the sky." },
      { who: 'luma', cam: 'two',
        say: "A circle around a courtyard. Who is it for?" },
      { who: 'karl', cam: 'cu',
        slide: { kicker: 'Heritage', title: 'Meeting in a circle', lines: ['Gathering in a circle, round a fire or a yard', 'Everyone faces the middle', 'Here: rooms round an open courtyard'] },
        say: "It's a place to gather. People have always met in a circle, round a fire or a yard, everyone facing the middle. Here the rooms go round the ring and all of them look into the courtyard." },
      { who: 'luma', cam: 'roof', look: 'roof',
        slide: { kicker: 'Roof lights', title: 'Twin panels on the rim', lines: ['Two panels in the ring roof', 'Hinged on the centre line', 'They open into a shallow V'] },
        say: "And there's a roof light even with a hole in the roof?" },
      { who: 'karl', cam: 'roof', look: 'roof', open: 1,
        say: "The courtyard lights the inside edge. For the rooms at the back we put twin panels in the ring. They open into a shallow V and bring light and air into the deepest part of the plan." },
      { who: 'luma', cam: 'cu', mood: 'smile',
        say: "The sheet says final engineering specifications. Are we there?" },
      { who: 'karl', cam: 'cu', mood: 'serious', slide: HONEST,
        say: "Honestly, no. That's the heading of the concept sheet. The proven part is LB-1: 555 newtons of lift, 1,544 of wind hold, and the laminated glass. The ring roof is a big span, and the engineer designs it before we call anything final." },
      { who: 'luma', cam: 'globe', look: 'globe', slide: CLIMATE(['Deep ring roof: shades the glass all round', 'Open courtyard: warm air rises out']),
        say: "A glass wall all the way round in Bulawayo heat?" },
      { who: 'karl', cam: 'cu',
        say: "The ring roof overhangs the glass all the way round, so it's in shade most of the day, and warm air rises out through the courtyard. The panels close when it rains." },
      { who: 'luma', cam: 'house', look: 'house', build: 0, open: 0,
        slide: BUILD('Ring Pavilion', ['Survey and soil test', 'Round plinth and courtyard', 'Red mullions and rings', 'Floor and ring roof']),
        say: "Let's build it." },
      { who: 'karl', cam: 'house', look: 'house', build: 1, point: true,
        say: "Soil test, the round plinth with the stone courtyard in the middle, then the red frames of the outer wall and the courtyard wall." },
      { who: 'karl', cam: 'house', look: 'house', build: 3,
        say: "The floor, then the ring roof, thick and white, with its rounded edges." },
      { who: 'karl', cam: 'house', look: 'house', build: 5, slide: CLOSE,
        say: "Glass into both walls, then the interior." },
      { who: 'karl', cam: 'roof', look: 'roof', build: 7,
        say: "And the twin panels in the rim, water-tested before handover." },
      { who: 'luma', cam: 'screen', look: 'screen',
        slide: { kicker: 'Materials list', title: 'What goes into the Ring', lines: ['Concrete plinth, stone courtyard', 'Red steel mullions and rings', 'Curved glazing, two walls', 'Concrete ring roof, white finish', 'Twin roof panels, actuators'] },
        ticker: ['Concrete plinth', 'Stone courtyard paving', 'Steel mullions and ring beams, red finish', 'Curved glazing in aluminium frames', 'Concrete ring roof', 'Twin roof panels', 'Seals and actuators', 'Rain sensor + battery backup'],
        say: "Here's the materials list." },
      { who: 'luma', cam: 'wide', open: 1, mood: 'smile', slide: next('The Zambezi Curve Pavilion', 'Victoria Falls'),
        say: "The Ring Pavilion. Next time, the season finale, on the Zambezi. I'm Luma." },
      { who: 'karl', cam: 'wide', mood: 'smile',
        say: "And I'm Karl. Don't miss the last one." }
    ]
  }, {
    /* ================= S2 EPISODE 10 — Zambezi Curve Pavilion · Victoria Falls ================= */
    id: 's2e10-zambezi', no: 10, season: 2,
    title: 'The Zambezi Curve Pavilion',
    subtitle: 'Season 2 · Episode 10 · Victoria Falls · Flow and structure',
    concept: 'zambezi-curve-pavilion', city: 'vicfalls',
    lines: [
      { who: 'luma', cam: 'wide', build: 7, open: 0, mood: 'smile', look: 'globe',
        slide: { kicker: 'Season 2 · Episode 10 · Victoria Falls', title: 'The Zambezi Curve Pavilion', lines: ['A double-curved white shell', 'Red steel arch ribs', 'Solar roof leaves over the crest'] },
        say: "Welcome to the season two finale. The Atlas has flown us to Victoria Falls, on the Zambezi, and our last building looks like water." },
      { who: 'karl', cam: 'house', look: 'house', point: true,
        say: "The Zambezi Curve Pavilion. One white shell, curved two ways, rising into a high open arch on one side and sweeping down to a curled tip on the other. Underneath, red steel arch ribs carry it." },
      { who: 'luma', cam: 'two',
        say: "It does look like a wave." },
      { who: 'karl', cam: 'cu',
        slide: { kicker: 'Heritage', title: 'The Zambezi', lines: ['Mosi-oa-Tunya: the smoke that thunders', 'Water over rock', 'A shell shaped by that flow'] },
        say: "That's the Zambezi in it. At the Falls the river pours over the rock, Mosi-oa-Tunya, the smoke that thunders. We wanted a roof that feels like water running over stone." },
      { who: 'luma', cam: 'cu',
        say: "And the red frames underneath?" },
      { who: 'karl', cam: 'cu',
        say: "Arch ribs, each one a pair of curved chords with bracing between them. A curved shell is strong for its weight, and the ribs hold its shape. Open on all sides, so the breeze goes straight through." },
      { who: 'luma', cam: 'roof', look: 'roof',
        slide: { kicker: 'Roof light', title: 'A solar butterfly', lines: ['An opening at the crest of the shell', 'Two leaves of solar glass', 'They lift, then open into a V'] },
        say: "And the finale roof." },
      { who: 'karl', cam: 'roof', look: 'roof', open: 1,
        say: "At the crest there's an opening, covered by two leaves of solar glass. Watch. They lift clear of the shell, then open into a V, and the sun comes down into the middle while the leaves keep making power." },
      { who: 'luma', cam: 'cu', mood: 'smile',
        say: "A roof light that makes its own electricity." },
      { who: 'karl', cam: 'cu', mood: 'serious', slide: HONEST,
        say: "That's the idea, and it's a concept. The actuators and glass we've proven on LB-1. Solar leaves are heavier and carry cables through the hinge, so they need their own design and testing before anyone quotes a number." },
      { who: 'luma', cam: 'globe', look: 'globe', slide: CLIMATE(['Spray and humidity near the Falls', 'Open sides: breeze, no trapped heat']),
        say: "Spray from the Falls, heat, humidity. What does that do to it?" },
      { who: 'karl', cam: 'cu',
        say: "Steel needs a proper protective coating near all that spray, and the shell sheds water off both edges. Open sides mean no trapped heat. And the leaves close themselves in a storm." },
      { who: 'luma', cam: 'house', look: 'house', build: 0, open: 0,
        slide: BUILD('Zambezi Pavilion', ['Survey and soil test', 'Ground slab', 'Red arch ribs', 'The shell and its crest opening']),
        say: "One last build, Karl." },
      { who: 'karl', cam: 'house', look: 'house', build: 1, point: true,
        say: "Soil test, the ground slab, then the red arch ribs, five of them, and the legs where the shell comes down." },
      { who: 'karl', cam: 'house', look: 'house', build: 3,
        say: "Then the shell goes over the ribs, curving two ways, with the opening at the crest." },
      { who: 'karl', cam: 'house', look: 'house', build: 5, slide: CLOSE,
        say: "The floor finishes and the furniture underneath." },
      { who: 'karl', cam: 'roof', look: 'roof', build: 7,
        say: "And the solar leaves at the crest, tested on the rig before handover." },
      { who: 'luma', cam: 'screen', look: 'screen',
        slide: { kicker: 'Materials list', title: 'What goes into the Pavilion', lines: ['Concrete ground slab', 'Red steel arch ribs, coated', 'Double-curved shell, white finish', 'Solar glass leaves in red frames', 'Actuators, rain sensor, battery'] },
        ticker: ['Concrete ground slab', 'Steel arch ribs, red finish, protective coating', 'Double-curved shell, white finish', 'Crest opening with red frame', 'Solar glass leaves', 'Actuators, seals, cabling', 'Rain sensor + battery backup'],
        say: "The last materials list of the season." },
      { who: 'luma', cam: 'two',
        say: "Ten buildings this season. Your favourite, Karl?" },
      { who: 'karl', cam: 'cu', mood: 'smile',
        say: "The one somebody asks me to build first. Message us on Instagram." },
      { who: 'luma', cam: 'wide', open: 1, mood: 'smile',
        slide: { kicker: 'Next · Episode 11', title: 'From Stand to Keys', lines: ['Six episodes, one house', 'From an empty stand to the keys', 'Follow @karlcon_lumen_builds_zw'] },
        say: "That's the Heritage Studio Series, ten buildings rooted in Zimbabwe. But season two isn't finished. Next time we start From Stand to Keys, one house built from an empty stand to the day you get the keys. I'm Luma." },
      { who: 'karl', cam: 'wide', mood: 'smile',
        say: "And I'm Karl. If you're planning to build, don't miss it." }
    ]
  }];
})();
